### ISSUE TITLE
Support for payment apps

### ISSUE THREAD

**Issue by korycins** [saleor/saleor#11258]
The scope of this RFC is to provide a better way of processing payments via Saleor apps. The base assumption is that we want to have a replacement for the payment plugin flow which is not enough flexible and hard to maintain.  The proposed flow will operate on `TransactionItem` and extend the `TransactionAPI`. 

> **Note**
> If you are not familiar with the feature, see section 4. that described the workflow.

```[tasklist]
### Tasks
- [ ] https://github.com/saleor/saleor/issues/12016
- [ ] https://github.com/saleor/saleor/issues/12021
- [ ] https://github.com/saleor/saleor/issues/12017
- [ ] https://github.com/saleor/saleor/issues/12022
- [ ] https://github.com/saleor/saleor/issues/12018
- [ ] https://github.com/saleor/saleor/issues/12023
- [ ] https://github.com/saleor/saleor/issues/12143
- [ ] https://github.com/saleor/saleor/issues/12020
- [ ] https://github.com/saleor/saleor/issues/12024
- [ ] https://github.com/saleor/saleor/issues/12303
- [ ] https://github.com/saleor/saleor/issues/12019
- [ ] https://github.com/saleor/saleor/issues/12316
- [ ] https://github.com/saleor/saleor/issues/12305
- [ ] https://github.com/saleor/saleor/issues/12168
- [ ] https://github.com/saleor/saleor/issues/12306
```

# 1. General Assumptions

- checkout flow can be finalized by using payment apps
- checkout flow can use `TransactionItem` objects to process a payment
- checkout flow can handle split payments

# 2. API Changes
### 2.1 PaymentGatewayInitialize
Required permission: -
```graphql
scalar JSON

enum PaymentGatewayConfigErrorCode {
  GRAPHQL_ERROR
  INVALID
  NOT_FOUND
}


type PaymentGatewayConfigError {
  """
  Name of a field that caused the error. A value of `null` indicates that the error isn't associated with a particular field.
  """
  field: String

  """The error message."""
  message: String


  """The error code."""
  code: PaymentGatewayConfigErrorCode!
}


type PaymentGatewayConfig {
  id: String!,
  errors: [PaymentGatewayConfigError!]!
  data: JSON
}


type PaymentGatewayInitialize {
  gatewayConfigs: [PaymentGatewayConfig!]!
}

input PaymentGatewayToInitialize {
  id: String!
  data: JSON
}


type Mutation{
  paymentGatewayInitialize(
    """
    The ID of the related object. For now only checkout is supported.
    """
    id: ID!
    """
    When amount is not provided we use amount = checkout.total - transactions that are already processed
    """
    amount: Decimal

    """
    Optionally user can decide which payment gateway should be initialized.
    """
    paymentGateways: [PaymentGatewayToInitialize!]
  ): PaymentGatewayInitialize
}
```
### 2.2 TransactionInitialize
Required permission: - or HANDLE_PAYMENTS in case of providing `transactionInitialize.action`
```graphql

enum TransactionInitializeErrorCode {
  GRAPHQL_ERROR
  INVALID
  NOT_FOUND
}


type TransactionInitializeError {
  """
  Name of a field that caused the error. A value of `null` indicates that the error isn't associated with a particular field.
  """
  field: String

  """The error message."""
  message: String


  """The error code."""
  code: TransactionInitializeErrorCode!
}

type TransactionInitialize {
  transaction: TransactionItem!
  event: TransactionEvent!
  errors: TransactionInitializeError
}

enum TransactionFlowStrategy{
  AUTHORIZATION
  CHARGE
}

type Mutation{
  transactionInitialize(
    """
    The ID of the related object. For now only checkout is supported.
    In the future we could also use order?
    """
    id: ID!

    """
    When amount is not provided we use amount = checkout.total - transactions that are already processed
    """
    amount: Decimal

    """
    By default we take the settings from channel. If there is an app token we can overwrite the channel setting
    """
    action: TransactionFlowStrategy
    paymentGateway: PaymentGatewayToInitialize!
  ): TransactionInitialize
}
```
### 2.3 TransactionProcess
Required permission: -
```graphql
enum TransactionProcessErrorCode {
  GRAPHQL_ERROR
  INVALID
  NOT_FOUND
}

type TransactionProcessError {
  """
  Name of a field that caused the error. A value of `null` indicates that the error isn't associated with a particular field.
  """
  field: String

  """The error message."""
  message: String


  """The error code."""
  code: TransactionProcessErrorCode!
}

type TransactionProcess {
  transaction: TransactionItem
  event: TransactionEvent
  errors: TransactionProcessError
}

type Mutation {
  transactionProcess(
    """
    The ID of the transactionItem
    """
    id: ID!
    data: JSON
  ): TransactionProcess
}
```
### 2.4 Channel type
```graphql

type Channel implements Node {
  ...
  defaultTransactionFlowStrategy: TransactionFlowStrategy!

}
```
### 2.5 ChannelUpdate
Required permission: MANAGE_CHANNELS or HANDLE_PAYMENTS (in case of updating only strategy)
```graphql
input ChannelUpdateInput {
  ...
  defaultTransactionFlowStrategy: TransactionFlowStrategy
}
```
### 2.6 ChannelCreate
Required permission: MANAGE_CHANNELS

```graphql
input ChannelCreateInput {
  ...
  defaultTransactionFlowStrategy: TransactionFlowStrategy
}
```
### 2.7 Checkout
Required permission: -
```graphql
type Checkout {
  """
  Deprecated, use updatedAt instead.
  """
  lastChange: DateTime! 
  updatedAt: DateTime!
  """
  The difference between the paid and the checkout total amount.
  """
  totalBalance: Money
  
    """
  The authorize status of the checkout.
  
  Added in Saleor 3.13.
  
  Note: this API is currently in Feature Preview and can be subject to changes at later point.
  """
  authorizeStatus: CheckoutAuthorizeStatusEnum!

  """
  The charge status of the checkout.
  
  Added in Saleor 3.13.
  
  Note: this API is currently in Feature Preview and can be subject to changes at later point.
  """
  chargeStatus: CheckoutChargeStatusEnum!
}

enum CheckoutChargeStatusEnum {
  NONE
  PARTIAL
  FULL
  OVERCHARGED
}

enum CheckoutAuthorizeStatusEnum {
  NONE
  PARTIAL
  FULL
}

input CheckoutFilterInput {
  ...
  updatedAt: DateRangeInput
  authorizeStatus: [CheckoutAuthorizeStatusEnum!]
  chargeStatus: [CheckoutChargeStatusEnum!] 
}
```

# 3. Webhooks
#### Request body
```graphql
scalar JSON
type PaymentGatewayInitializeSession {
      """Time of the event."""
  issuedAt: DateTime

  """Saleor version that triggered the event."""
  version: String

  """The user or application that triggered the event."""
  issuingPrincipal: IssuingPrincipal

  """The application receiving the webhook."""
  recipient: App
  
  """Checkout or order"""
  sourceObject: OrderOrCheckout!

  """Payment gateway data in JSON format, recieved from storefront."""
  data: JSON

  """Amount requested for initializing the payment gateway."""
  amount: PositiveDecimal
 }

 union OrderOrCheckout = Checkout | Order
```
#### Response body
```
{
  data: JSON
}
```
#### Request body
```graphql
type TransactionInitializeSession implements Event {
   """Time of the event."""
   issuedAt: DateTime

   """Saleor version that triggered the event."""
   version: String

   """The user or application that triggered the event."""
   issuingPrincipal: IssuingPrincipal

   """The application receiving the webhook."""
   recipient: App

   """Look up a transaction."""
   transaction: TransactionItem!

   """Checkout or order"""
   sourceObject: OrderOrCheckout!

   """Payment gateway data in JSON format, recieved from storefront."""
   data: JSON

   """Merchant reference assigned to this payment."""
   merchantReference: String!

   """Action to proceed for the transaction"""
   action: TransactionProcessAction!
 }

 type TransactionProcessAction {
   """Transaction amount to process."""
   amount: PositiveDecimal!

   """Currency of the amount."""
   currency: String!
   actionType: TransactionFlowStrategyEnum!
 }

 """
 Determine the transaction flow strategy.

     AUTHORIZATION - the processed transaction should be only authorized
     CHARGE - the processed transaction should be charged.
 """
 enum TransactionFlowStrategyEnum {
   AUTHORIZATION
   CHARGE
 }
```
#### Response body
```
{
  pspReference: String!
  data: JSON,
  result: Union[ CHARGE_SUCCESS, CHARGE_FAILURE, CHARGE_REQUEST, AUTHORIZATION_SUCCESS, AUTHORIZATION_FAILURE, AUTHORIZATION_REQUEST, AUTHORIZATION_ACTION_REQUIRED, CHARGE_ACTION_REQUIRED]!
  amount: PositiveDecimal!
  time: DateTime
  externalUrl: String
  message: String
}
```
#### Request body
```graphql
type TransactionProcessSession {
    """Time of the event."""
  issuedAt: DateTime

  """Saleor version that triggered the event."""
  version: String

  """The user or application that triggered the event."""
  issuingPrincipal: IssuingPrincipal

  """The application receiving the webhook."""
  recipient: App

  pspReference: String!

  """Look up a transaction."""
  transaction: TransactionItem!

  """Checkout or order"""
  sourceObject: OrderOrCheckout!

  """Payment gateway data in JSON format, recieved from storefront."""
  data: JSON

  """Merchant reference assigned to this payment."""
  merchantReference: String!

  """Action to proceed for the transaction"""
  action: TransactionProcessAction!
}
```
#### Response body
```
{
  pspReference: String!
  data: JSON,
  result: Union[ CHARGE_SUCCESS, CHARGE_FAILURE, CHARGE_REQUEST, AUTHORIZATION_SUCCESS, AUTHORIZATION_FAILURE, AUTHORIZATION_REQUEST, AUTHORIZATION_ACTION_REQUIRED, CHARGE_ACTION_REQUIRED]!
  amount: PositiveDecimal!
  time: DateTime
  externalUrl: String
  message: String
}
```
### 3.4 checkout-fullypaid [ASYNC]
```graphql
type CheckoutCreated implements Event {
  """Time of the event."""
  issuedAt: DateTime

  """Saleor version that triggered the event."""
  version: String

  """The user or application that triggered the event."""
  issuingPrincipal: IssuingPrincipal

  """The application receiving the webhook."""
  recipient: App

  """The checkout the event relates to."""
  checkout: Checkout
}
```
# 4. Workflow
## 4.1 Diagram
```mermaid
sequenceDiagram
  Front->>+Saleor: Fetch <br>checkout.availablePaymentGateways
	Saleor -->>- Front: List of the paymentGatewyas<br> with included payment app
	Front ->> Saleor: Mutation PaymentGatewayInitialize,<br>amount, list of<br>payment gateways IDs<br>to initialize and <br>data, if<br>old ID provided, return<br>error
	Saleor ->>+ PaymentApp: payment-gateway-initialize-session<br>webhook
	PaymentApp -->>- Saleor: PaymentGateway data with config
	Saleor -->> Front: List of PaymentGateways
	Front ->>+ Saleor: TransactionInitialize<br>(like checkoutPymentCreate)<br> with amount and<br>payment gateway ID, data
	Saleor ->> Saleor: Create TransactionItem
	Saleor ->> Saleor: Request TransactionEvent created
  Saleor ->>+ PaymentApp: webhook transaction-initialize-session
	PaymentApp -->>- Saleor: mandatory data for init the frontend
	Saleor ->> Saleor: TransactionEvent <br>created/TransactionEvent<br>request updated
	Saleor -->>- Front: TransactionItem created
	Front ->>+ PaymentProvider: Process a payment
	PaymentProvider -->>- Front: additional action required
	Front ->> Saleor: TransactionProcess
	Saleor ->>+ PaymentApp: transaction-process-session webhook
	PaymentApp -->>- Saleor: success
	Saleor ->> Saleor: Create the TransactionEvent
	Saleor -->> Front: Return success
	Front ->>+ Saleor: call checkoutComplete
	Saleor -->>- Front: Order created
```
## 4.2 Example flow with Adyen, only authorize the funds and capture them with external service. 
The below chart is only a sample, when we have a separate service that will exectue a charge on customer's funds
```mermaid
sequenceDiagram
    Frontend ->>+ Saleor: Get checkout
    Saleor -->>- Frontend: Checkout
    Frontend ->>+ Saleor: Initialize<br>payment<br>gateway
    Saleor ->>+ AdyenApp: Webhook <br> PaymentGatewayInitializeSession
    AdyenApp ->>+ Adyen: Fetch available<br>payment methods
    Adyen -->>- AdyenApp: Drop-in data
    AdyenApp -->>- Saleor: Drop-in data
    Saleor -->>- Frontend: Data from<br>AdyenApp
    Frontend ->> Frontend: Initialize drop-in
    loop Until user details are not valid 
        Frontend ->>+ Saleor: User enter details
        Saleor -->>- Frontend: Resonse
    end
    Frontend ->> Saleor: transactionIntialize
    Saleor ->> Saleor: create TransactionItem
    Saleor ->>+ AdyenApp: Webhook <br> TransactionInitializeSession
    AdyenApp ->>+ Adyen: Start processing<br>payment
    Adyen -->>- AdyenApp: Mandatory data to<br>finalize the payment
    AdyenApp ->>- Saleor: Data mandatory<br>to finalize<br>the payment
    Saleor -->> Frontend: TransactionItem and data from app
    Frontend ->>+ Adyen: Process <br>additional<br>actions
    Adyen -->>- Frontend: Data
    Frontend ->>+ Saleor: transactionProcess<br>with data
    Saleor ->>+ AdyenApp: Webhook <br> TransactionProcessSession
    AdyenApp ->>+ Adyen: Process additional<br>actions
    Adyen -->>- AdyenApp: Payment finalized
    AdyenApp -->>- Saleor: AUTHORIZATION_SUCCESS
    Saleor -->>- Frontend: Transaction processed
    Frontend ->>+ Saleor: checkoutComplete
    Saleor -->>- Frontend: Order
    Saleor ->>+ ExternalService: Webhook with order<br>details and psp<br>reference
    ExternalService -->>- Saleor: OK
    ExternalService ->> Adyen: Capture funds
    Adyen ->> AdyenApp: Adyen notification about<br>capture
    AdyenApp ->> Saleor: Report change<br>for transaction<br> about<br>sucessfull charge
```
## 4.3 Step by step
1. User/Storefront calls `checkout.availablePaymentGateways`. Saleor discovers the apps that are marked as an app that can process the payment, then returns them as `PaymentGateway` type.
2. User/Storefront decides which payment gateways should be initialized. Then calls `paymentGatewayInitialize` with the list of paymentGateways IDs and optional `data` that will be passed to a specific payment app. Saleor passes the `data` to the App inside the sync webhook `PaymentGatewayInitializeSession`. PaymentApp can return additional data that Saleor will pass to the front end.
3. User/Storefront decides which payment gateway will be used, and call `transactionInitialize` mutation, with the amount that want to cover. If amount is not provided, Saleor will use checkout.balance to define the proper amount. The additional data for PaymentApp can be passed via the input: `transactionInitialize.paymentGateway.data`. Providing `action` requires an additional permission. The mutation will create `TransactionItem` and request `TransactionEvent` object. Saleor will send sync webhook `TransactionInitializeSession`.  The payment app need to return a pspReference and the result of the action. If any additional actions are still required returned `result` field should contain the value `AUTHORIZATION_ACTION_REQUIRED ` or `CHARGE_ACTION_REQUIRED`. The `data` field returned by Payment app will be passed to the frontend as an `TransactionEvent` object.
4. To process additional actions requested by the payment provider, user/storefront should use `transactionProcess` mutation. Calling `transactionProcess` mutation will trigger a webhook `TransactionProcessSession`. The structure and response have the same format as for `TransactionInitializeSession`. If there are any additional actions that the user needs to proceed with, then `transactionProcess` should be called again.
5. After resolving the processing payment(s), user/storefront should call checkoutComplete mutation. If everything is correct, the order will be created. 
# 5. Migration guide

To proceed with migration, the app that has support for specific payment providers needs to be installed. 
The detailed workflow will depend on the implemntation of the payment app. 
The usage of `checkoutPaymentCreate` should be replaced with calls `paymentGatewayInitialize` and `transactionInitialize`.
Instead of multiple calling `checkoutComplete` (in case of additional actions required from the user), the `transactionProcess` should be called.
`checkoutComplete` should be called only once when the checkout.balance == 0. The mutation will create the order.

# 6 Acceptance Criteria:

- To use this feature, an app with an identifier is required.
- The app can subscribe to new SYNC webhooks: `PAYMENT_GATEWAY_INITIALIZE_SESSION`, `TRANSACTION_INITIALIZE_SESSION`, `TRANSACTION_PROCESS_SESSION`.
- The new webhooks require `HANDLE_PAYMENTS` permissions.
- The new webhooks use subscription types: `PaymentGatewayInitializeSession`, `TransactionInitializeSession`, and `TransactionProcessSession`.
- The new webhooks allow fetching fields in the payload, such as `checkout.totalPrice`. By default, this is not allowed in a SYNC payload.
- Calling `checkout.availablePaymentGateways` will return the `app`s with the identifier and the existing subscription for `TransactionInitializeSession`.
- Calling the `PaymentGatewayInitialize` mutation will:
    - Send the webhook `PaymentGatewayInitializeSession` if `paymentGateways` are provided. The `data` defined in the structure will be sent in the webhook.
    - Send the `data` provided for a specific app only to the requested app if `paymentGateways` has multiple apps declared.
    - Send the SYNC webhook to all existing apps that are subscribed to `PaymentGatewayInitializeSession` if `paymentGateways` are not provided.
    - Return the response returned by each app from the sync request in the mutation, inside the field `gatewayConfigs`. The response structure is defined in section 3.1.
- Calling the `transactionInitialize` mutation will:
    - Send the webhook `TransactionInitializeSession`.
    - Send the webhook only to the app provided in the input `paymentGateway`.
    - Pass the `data` provided to the app as a webhook payload if `paymentGateway.data` is provided.
    - Allow providing `transactionInitialize.action` as an input only when the mutation is called by the app with `HANDLE_PAYMENTS`.
    - Return the response structure defined in section 3.2.
    - Pass `response.data` directly to the frontend inside the `transactionInitialize` mutation response.
    - Create different events based on `response.result`:
        - CHARGE_SUCCESS/`AUTHORIZATION_SUCCESS` will include the amount in `transaction.chargedAmount` / `transaction.authorizedAmount`.
        - CHARGE_REQUEST/`AUTHORIZATION_REQUEST` will include the amount in `transaction.chargePendingAmount` / `transaction.authorizePendingAmount`.
        - FAILURE events do not change anything.
        - `AUTHORIZATION_ACTION_REQUIRED`/ `CHARGE_ACTION_REQUIRED` means that additional action from the user is required.
    - Return `transactionItem` & `transactionEvent` as a mutation response.
    - In case when Saleor can’t connect to the app, or the response has incorrect response, the failure event will be created and assigned to the transaction.
- Calling the `transactionProcess` mutation will:
    - Use `transactionProcess` in case when `transactionInitialize` returns the event `AUTHORIZATION_ACTION_REQUIRED`/ `CHARGE_ACTION_REQUIRED`. Send the mutation after processing additional actions by the user.
    - Send the webhook `TransactionProcessSession`.
    - Send the webhook only to the app used in `transactionInitialize`
    - Pass the `data` provided to the app as a webhook payload if `data` is provided.
    - Return the response structure defined in section 3.3.
    - Pass `response.data` directly to the frontend inside the `transactionInitialize` mutation response.
    - Create the same actions based on `response.result` as for `transactionInitialize`.
    - Return `transactionItem` & `transactionEvent` as a mutation response.
    - In case when Saleor can’t connect to the app, or the response has incorrect response, the failure event will be created and assigned to the transaction.
- Checkout:
    - Checkout completion:
        - `checkoutComplete` accepts the checkout that is paid with a transaction.
        - `checkoutComplete` should return the order when the checkout is fully authorized.
    - The webhook `CHECKOUT_FULLY_PAID` should be called when checkout.transactions cover the checkout.total. `Cover` means that funds are authorized, charged, or in a pending state.
    - The checkout has two statuses:
        - `authorizeStatus`:
            - `FULL` when the sum of (authorized, charged, and pending amounts) covers the checkout total.
            - `PARTIAL` when the sum of (authorized, charged, and pending amounts) partially covers the checkout total.
            - `NONE` when no funds are covered by transactions.
        - `chargeStatus`:
            - `FULL` when the sum of (charged and pending charge) covers the checkout total.
            - `PARTIAL` when the sum of (charged and pending charge) partially covers the checkout total.
            - `NONE` when the sum of (charged and pending charge) is 0.
- Channel:
    - A new field is added: `defaultTransactionFlowStrategy`.
    - The `defaultTransactionFlowStrategy` controls the `action` field included in `TRANSACTION_INITIALIZE_SESSION` and `TRANSACTION_PROCESS_SESSION`. If the `action` field is not overwritten by the app that calls the mutation, it will use the `defaultTransactionFlowStrategy`.
    - To update the field, `MANAGE_CHANNELS` or `HANDLE_PAYMENTS` is required.
- TransactionItem:
    - will use `ID` build with `UUID` (previously it was `int`)
    - The new API will accept only the `id` for new transaction
    - The transaction created before introducing this feature will not work with a new API
    - The transaction with old `ID` can use `transactionUpdate` and `TransactionRequestAction` mutations

**Comment by mmiszy** [comment]
> action: TransactionFlowStrategy

I think we should rename the field and use consistent names everywhere. If it's a "transaction flow strategy", let's call the field `transactionFlowStrategy: TransactionFlowStrategy`.

---

> TransactionProcessErrorCode

Is it defined anywhere?

---

> transactionProcess

How do we know to which Payment App should the `data` be passed? Do we store Payment Gateway ID on PaymentItem?

---

> defaultTransactionStrategy: TransactionFlowStrategy!

Ditto, I think we should change it to `defaultTransactionFlowStrategy: TransactionFlowStrategy!`

---

> TransactionProcessAction

```graphql
type TransactionProcessAction {
  actionType: TransactionFlowStrategy!
  amount: PositiveDecimal!
  currency: String!
}
```

Wondering if we should use the `Money` type here instead (and rename `actionType`):

```graphql
type TransactionProcessAction {
  transactionFlowStrategy: TransactionFlowStrategy!
  value: Money!
}
```

---

> Saleor discovers the apps that are marked as an app that can process the payment

…based on which apps subscribed to the `PaymentGatewayInitializeSession` subscription.

**Comment by korycins** [comment]
@mmiszy Thanks for the feedback!

> >action: TransactionFlowStrategy

>I think we should rename the field and use consistent names everywhere. If it's a "transaction flow strategy", let's call the field transactionFlowStrategy: TransactionFlowStrategy.

Maybe you have better name than `TransactionFlowStrategy`. The `TransactionAction` is already used. Also personally I would keep the `action` field, as we use everywhere the `action` field (`TransactionActionRequest` mutation and inside the transaction webhooks).

------

>> TransactionProcessErrorCode

>Is it defined anywhere?

Right, I missed that. Thanks


------

>> transactionProcess

> How do we know to which Payment App should the data be passed? Do we store Payment Gateway ID on PaymentItem?

Inside TransactionInitialize user provides the `paymentGateway`. We will attach the `app` to the newly created transaction.
So each next call on `transactionProcess` will already have the all details related to the app.

------

>> defaultTransactionStrategy: TransactionFlowStrategy!

>Ditto, I think we should change it to defaultTransactionFlowStrategy: TransactionFlowStrategy!

Sounds good

------

>>TransactionProcessAction
```graphql
type TransactionProcessAction {
  actionType: TransactionFlowStrategy!
  amount: PositiveDecimal!
  currency: String!
}
```
>Wondering if we should use the Money type here instead (and rename actionType):
```graphql
type TransactionProcessAction {
  transactionFlowStrategy: TransactionFlowStrategy!
  value: Money!
}
```
The proposed structure is the same as we use for already existing webhook `TransactionActionRequest`(introduced in 3.4) (and the new ones that we're going to merge). If we want to change this, then I think that we should change them in all new incoming webhooks (so would be good to agree thiis with whole team).

**Comment by witoszekdev** [comment]
> ```graphql
> type Mutation{
>   transactionInitialize(
>     # ...
>     """
>     When amount is not provided we use amount = checkout.total - transactions that are already processed
>     """
>     amount: Decimal
>     # ...
>   ): TransactionInitialize
> }
> ```
What qualifies as "processed" transaction? Is it:
a. a transaction has `transactionProcess` mutation called with ID of that transaction?
b. a transaction that has `authorizePending` or `chargePending` amounts?
c. a transaction that has `authorized` or `charged` amounts?

> ```graphql
> type Mutation{
>   transactionInitialize(
>     # ...
>     """
>     By default we take the settings from channel. If there is an app token we can overwrite the channel setting
>     """
>     action: TransactionFlowStrategy
>     # ...
>   ): TransactionInitialize
> }
> ```
What happens if a regular user / a guest uses `action` inside this mutation? Do we raise a permission exception, or is this value silently ignored?

Is the `setCustomerExternalReference` saved anywhere at this point, or did I miss something?

What is this webhook in the Adyen chart:
![CleanShot 2023-01-31 at 15 38 32@2x](https://user-images.githubusercontent.com/4144459/215790588-8de8e4bb-e542-43c5-9305-5f2cdfb47de0.png)

> Saleor will send sync webhook TransactionInitializeSession. The payment app need to return a pspReference and the result of the action. If any additional actions are still required returned **`result` field should contain the value "charge-requested" or "authorization-requested"**.

Is this right? From the RFC the `result` field should be a union, and there's no `charge-requested` or `authorization-requested` there. Maybe those additional actions should be handled by whatever is passed in the `data` field?

**Comment by korycins** [comment]
@witoszekdev 
> What qualifies as "processed" transaction? Is it:
a. a transaction has transactionProcess mutation called with ID of that transaction?
b. a transaction that has authorizePending or chargePending amounts?
c. a transaction that has authorized or charged amounts?

The proper status of the event. The `transactionIntialize` and `transactionProcess`, returns the event. If the event is authorize_success, or authorize_charge. It means that you have sucesfull processed transaction.

> What happens if a regular user / a guest uses action inside this mutation? Do we raise a permission exception, or is this value silently ignored?

Good question. I would say, that we should raise an exception.

> Is the setCustomerExternalReference saved anywhere at this point, or did I miss something?

I need to drop it from this RFC, as this is not a scope of storing the payment method.

> What is this webhook in the Adyen chart:

It is only a sample, when you have an external service responsible for charging the funds.

> Is this right? From the RFC the result field should be a union, and there's no charge-requested or authorization-requested there. Maybe those additional actions should be handled by whatever is passed in the data field?

It should be in upper cases. I will correct it.
```
result: Union[ CHARGE_SUCCESS, CHARGE_FAILURE, CHARGE_REQUESTED, AUTHORIZATION_SUCCESS, AUTHORIZATION_FAILURE, AUTHORIZATION_REQUESTED]!
```
