### ISSUE TITLE
Possibility to create a checkout based on existing order

### ISSUE THREAD

**Issue by korycins** [saleor/saleor#11352]
## Problem

There is no easy way to create a checkout from an order. Having this possibility would allow you to provide users with the option to reorder products based on an existing order.

---

## 1. General Assumptions

We would like to have an API to create checkout based on  existing order. This should cover a case when a customer often buys the same items. The new checkout should contain the all order's lines. For now, we can skip porting the user data like: addresses.

### Acceptance Criteria
- [ ] Customers can create a checkout by calling `checkoutCreateFromOrder` with the order ID.
- [ ] The checkout should contain all available variants that were added to the order.
- [ ] The quantity of a specific line should be the same as the quantity of specific order lines.
- [ ] `checkoutCreateFromOrder` doesn't require any permissions.
- [ ] The checkout should have a `user` assigned if `checkoutCreateFromOrder` is called as a logged-in user.
- [ ] Any unavailable variants will be attached in the mutation response `unavailableVariants` (product_unavailable_for_purchase, unavailable_variant_in_channel, product_not_published, quantity_greater_than_limit ,insufficient_stock) 
- [ ] User that calls the mutation will be attached to the newly created checkout (`checkout.user`, `checkout.email`)

## 2. API changes

``` graphql
type Mutation {
	checkoutCreateFromOrder(
		"""ID of existing order that will be used to create a checkout"""
		id: ID!
	)
}

type CheckoutCreateFromOrder @doc(category: "Checkout") {
  """Variants that were not attached to the checkout."""
  unavailableVariants: [CheckoutCreateFromOrderUnavailableVariant!]

  """Created checkout."""
  checkout: Checkout
  errors: [CheckoutCreateFromOrderError!]!
}

type CheckoutCreateFromOrderUnavailableVariant @doc(category: "Checkout") {
  """The error message."""
  message: String!

  """The error code."""
  code: CheckoutCreateFromOrderUnavailableVariantErrorCode!

  """Variant ID that is unavailable."""
  variantId: ID!

  """Order line ID that is unavailable."""
  lineId: ID!
}

enum CheckoutCreateFromOrderUnavailableVariantErrorCode @doc(category: "Checkout") {
  NOT_FOUND
  PRODUCT_UNAVAILABLE_FOR_PURCHASE
  UNAVAILABLE_VARIANT_IN_CHANNEL
  PRODUCT_NOT_PUBLISHED
  QUANTITY_GREATER_THAN_LIMIT
  INSUFFICIENT_STOCK
}

type CheckoutCreateFromOrderError @doc(category: "Checkout") {
  """
  Name of a field that caused the error. A value of `null` indicates that the error isn't associated with a particular field.
  """
  field: String

  """The error message."""
  message: String

  """The error code."""
  code: CheckoutCreateFromOrderErrorCode!
}

"""An enumeration."""
enum CheckoutCreateFromOrderErrorCode @doc(category: "Checkout") {
  GRAPHQL_ERROR
  INVALID
  ORDER_NOT_FOUND
  CHANNEL_INACTIVE
  TAX_ERROR
}
```

## 3. Database changes

Not required

## 4. To Do list

```[tasklist]
### Tasks
- [x] Add mutation `checkoutCreateFromOrder`
- [x] Add tests to cover new mutation
```

**Comment by timuric** [comment]
@korycins looks nice! Few questions:
- Will it copy the billing and shipping data?
- Would all items be copied to checkout including shipped, returned etc?

**Comment by korycins** [comment]
@timuric 
> Will it copy the billing and shipping data?

I thought that for MVP, we will only add orderLines to the checkout. If we want to provide addresses as well, we need to handle the following scenarios:

- If userA is logged in and userA created the order, and userA called the mutation, we can create the checkout and attach the addresses since we know that the mutation was called by the order owner and we won't leak any data.
- If the order was created by userA, but userB calls the mutation, we can't attach the address details since the user calling the mutation doesn't have access to the order.user details.
- If the order was created by anonymous userA and another anonymous userB calls the mutation, we can't attach the address details since we don't know if userA is the same as userB.

The proposed way of handling addresses aligns with how we handle them when calling the `order(id:<id>)` query.

> Would all items be copied to checkout including shipped, returned etc?

I'm not sure I understand. When you say `shipped` or `returned`, are you referring to the lines that have been shipped or returned?

Regardless of what happens to the specific order lines, we create the checkout based on them.

There is one case in which we are unable to copy all order lines: when a variant is not available in a specific channel. To address this issue, the mutation includes a flag that allows you to control whether to skip the unavailable variants or raise an exception if any variant is not available.
