### ISSUE TITLE
[RFC] Filters improvement

### ISSUE THREAD

**Issue by IKarbowiak** [saleor/saleor#11432]
The goal is to improve and clean up filters, which will allow specifying more complex conditions than at present.

### Add new `API` for filtering
- Replace `filter` with `where` option - deprecate `filter`, add new `where` option. Create new types input types for new filtering options 
- Move `search` from filters on the top level
- Introduce `AND`, `OR` and `NOT` operators
- Allow providing only `AND`, `OR`, `NOT` operators or just the field filter input; raise a ValidationError when those inputs are mixed on a single input object
- Introduce filtering input for basic types (`String`, `Int`, etc.) - for now, allow only filtering by `eq` and `oneOf` operation, add a validation - only one operator will be allowed to specify 
- The `date`, `dateTime`, and `Int` will also have the range option
- Each enum will have new filter input with `eq` and `oneOf` options 
- Raise a ValidationError when both `filters` and `where` options will be specified

### Assumptions regarding filters
- Every property of `API` types should be filterable
- Filter should be singular 
- Consistent naming of filters - the filter input field should have the same name in filtering as the property name in the API
- Every time a new field is added the new filter fields should be added
- Deprecate `sortBy` inside filters, the sorting option should be next to `filters`
- Nested connection fields should have the same filters as top levels, e.g. `Category.products`
- Deprecate the` product.variant` field - there is a top-level query for that
- Deprecate the following `Attribute` fields: `filterableInStorefront`, `storefrontSearchPosition`, `availableInGrid`.
- Add filters to fields that are not paginated (list fields)
- The guideline for filtering should be prepared. It should contain info about the following:
  - naming convention (as above: the filter input field should have the same name in filtering as the property name)
  - filter types convention (every time a new field is added the new filter fields should be added too)

### TODO list for each type

- [ ] Add new `WhereInput`
- [ ] Allow filtering be each field that is in the type definition
- [ ] Add `search` on the top-level, if it's available in filters options
- [ ] Deprecate `sortBy` inside filters, the sorting option should be next to `filters
- [ ] Extend the nested connections of field with the `where` option
- [ ] Add where filter to the list fields
- [ ] Add tests for each filtering field
- [ ] Add tests for operators filters
- [ ] Add benchmark test

 
## Progress

- [x] `Attribute` (#11737)
  Only missing:
   - [ ] benchmark tests
   - [ ] add `where` option on `attributes` fields of other types (`attributes` list fields that are not paginated)
- [ ] `AttributeValue`

## TODO

- [ ] performance tests - check the SQL statements for more advanced queries

### Examples
The following example queries demonstrate the use of `AND`, `OR`, and `NOT`  operators:
- The filter with the `NOT` and `AND` operators
> Attributes whose names are not `Author` and whose slug is not `tom` or `james`
```graphql
query {
   attributes(where: {NOT:  {AND: [{name: {eq: "Author"}}, {slug: {oneOf: ["tom", "james"]}}]}}) {
      edges {
          node {
             id
          } 
      }
   }
}
```
- The filter with `OR` operator
> Attributes that name is `Author` or `slug` is `tom` or `james`
```graphql
query {
   attributes(where: {OR: [{name: {eq: "Author"}}, {slug: {oneOf: ["tom", "james"]}}]} ) {
      edges {
          node {
             id
          } 
      }
   }
}
```
- The filter with `AND` and `OR` operator
> Attributes that are `PRODUCT_TYPE` type, and the id is `QXR0cmlidXRlOjIx` or `QXR0cmlidXRlOjI3` or the attribute name is `test`
```graphql
query {
  attributes(
    where: {
      AND: [
        {
          type: {
            eq:  PRODUCT_TYPE
          }
        },
        {
          OR: [
           {
             id: {
               oneOf: [ "QXR0cmlidXRlOjIx", "QXR0cmlidXRlOjI3"]
             }
           },
           {
             name: {
               eq: "test"
             }
           }
          ]
         }
      ],
    }
  ) {
    edges {
       node {
          id
          name
       }
    }
  }
}
```

### Invalid examples

**1.** Not allowed mixing of flat field filter and operator `AND`, `OR`, `NOT`
```graphql
query {
   attributes(where: {type: {eq: PRODUCT-TYPE}}, AND: [{name: {eq: "Author"}}]}) {
      edges {
          node {
             id
          }
      }
   }
}
```

**INSTEAD:** Join both conditions into one AND filter input
> Attributes that name is `Author` and type is `PRODUCT-TYPE`
```graphql
query {
   attributes(
    where: {
      AND: [
        {name: {eq: "Author"}},
        {type: {eq: PRODUCT_TYPE}}
      ]
    }
  ) {
      edges {
          node {
             id
          } 
      }
   }
}
```

**2.** Not allowed mixing operators on the same level 
```graphql
query {
   attributes(where: {NOT: {name: {eq: "Juice"}}, AND: [{type: {eq: PRODUCT-TYPE}}]}) {
      edges {
          node {
             id
          }
      }
   }
}
```
**INSTEAD:** Nest `NOT` condition inside `AND`
> Attributes that name is different than `Juice` and type is `PRODUCT-TYPE`
```graphql
query {
   attributes(where: {AND: [{NOT: {name: {eq: "Juice"}}}, {type: {eq: {PRODUCT-TYPE}}]}) {
      edges {
          node {
             id
          } 
      }
   }
}
```
**3.**  Not allowed mixing `filter` and `where` filters.
```graphql 
query {
   attributes(filter: {type: PRODUCT-TYPE}, where: {AND: [{name: {eq: "Author"}}]}) {
      edges {
          node {
             id
          }
      }
   }
}
```
**INSTEAD:** Use `filter` or `where`

**4.** Not allowed to mix different operations
```graphql 
query {
   attributes(where: {AND: [{name: {eq: "Author", oneOf: ["Author", "Juice"]}}]}) {
      edges {
          node {
             id
          }
      }
   }
}
```

Each new input filter will be added based on the below assumptions

## API changes

Below is an example of the API changes on the `Attribute` module based on the above assumptions. Changes in other modules will be presented in separate tickets.

#### Attribute
```graphql
type Query {
  attributes(
    # new
    where: AttributeWhereInput
    search: String

    # deprecate
    filter: AttributeFilterInput @(deprecate)
    
    # unchange
    sortBy: AttributeSortingInput
    channel: String
    before: String
    after: String
    first: Int
    last: Int
  ): AttributeCountableConnection
  ...
}

input AttributeWhereInput {
  AND: [AttributeWhereInput]
  OR: [AttributeWhereInput]
  NOT: AttributeWhereInput

  # I didn't use `IdFilterInput` here as there is an option to filter by single `id` in `attribute` query
  ids: [ID!]
  name: StringFilterInput
  slug: StringFilterInput
  withChoices: Boolean
  inputType: AttributeInputTypeEnumFilterInput
  entityType: AttributeEntityTypeEnumFilterInput
  type: AttributeTypeEnumFilterInput
  unit: MeasurementUnitsEnumFilterInput
  valueRequired: Boolean
  visibleInStorefront: Boolean
  filterableInDashboard: Boolean
  isVariantOnly: Boolean
  metadata: [MetadataFilter!]
  inCollection: ID
  inCategory: ID
}

type Attribute implements Node & ObjectWithMetadata {
  # deprecate
  availableInGrid: Boolean!  @derecate
  filteerableInStorefront: Boolean!   @derecate
  storefrontSearchPosition: Boolean!   @deprecate
  
  productTypes(
    # add
    where: ProductTypeWhereInput

    # unchange
    before: String
    after: String
    first: Int
    last: Int
  ): ProductTypeCountableConnection!

  productVariantTypes(
    # add
    where: ProductVariantWhereInput

    # unchange
    before: String
    after: String
    first: Int
    last: Int
  ): ProductTypeCountableConnection!
}

input AttributeInputTypeEnumFilterInput {
  eq: AttributeInputTypeEnum
  oneOf: [AttributeInputTypeEnum!]
}

input AttributeEntityTypeEnumFilterInput {
  eq: AttributeEntityTypeEnum
  oneOf: [AttributeEntityTypeEnum!]
}

input AttributeTypeEnumFilterInput {
  eq: AttributeTypeEnum
  oneOf: [AttributeTypeEnum!]
}

input MeasurementUnitsEnumFilterInput {
  eq: MeasurementUnitsEnum
  oneOf: [MeasurementUnitsEnum!]
}
```

#### New filter inputs of basic types
```graphql
input StringFilterInput {
  eq: String
  oneOf: [String!]
}

# validation - require only one value, raise an error otherwise
input IntFilterInput {
  eq: Int
  oneOf: [Int!]
  range: IntRangeInput
}

# one of argument is required, return ValidationError or just return empty queryset
input IntRangeInput{
  gte: Int
  lte: Int
}

input DateFilterInput {
  eq: Date
  oneOf: [Date!]
  range: DateRangeInput
}

# one of argument is required, return ValidationError or just return empty queryset
input DateRangeInput{
  gte: Date
  lte: Date
}

input DateTimeFilterInput {
  eq: DateTime
  oneOf: [DateTime!]
  range: DateTimeRangeInput
}

# one of argument is required, return ValidationError or just return empty queryset
input DateTimeRangeInput{
  gte: DateTime
  lte: DateTime
}
```

**Comment by fowczarek** [comment]
> Deprecate the product.variant field - there is a top-level query for that

Maybe we could add `product.variants_ids`  instead to allow easy get a list of all variants assigned to the product. Instead of iterating through `productVarinsts.edges.node.id`?

**Comment by korycins** [comment]
I am not convinced that we should deprecate the `product.variant` field. We just added it. The main idea was, to fetch the expected variant without additional query. Ref: https://github.com/saleor/saleor/issues/9452 
Also even if we decide to deprecate it: is it something related to the filter improvments?

---

>Replace filter with where option - deprecate filter, add new where option. Create new types input types for new filtering options

IMHO, `where` should be `PREVIEW_FEATURE`. We want to have a possibility to improve it based on the feedback. In that case, we shouldn't immediately deprecate the `filter` fields. If we do that, we will have to recommend using `where` which will not be "fully stable" until we will decide to remove `PREVIEW_FEATURE` label.

---

What is an expected way of handling queries with combined operators? For example the below one 👇  
```graphql
query {
  attributes(
    where: {
      type: {
        eq:  PRODUCT_TYPE
      }, {
      AND: [
        {
        	name: {
          	in: ["Test1", "Test"]
        	}
      	}
      ],
      NOT: [
        {
          slug: {
            in: ["Slug1", "Slug2"]
          }
        }
      ],
      OR: [
        {
           id: {
             in: [ "QXR0cmlidXRlOjIx", "QXR0cmlidXRlOjI3"]
           }
         },
        {
           name: {
             eq: "test"
           }
         }
      ]
    }
  )
...
```
Maybe we should start from preparing some doc that would explain potential combinations and expected result?

**Comment by IKarbowiak** [comment]
@patrys could you comment on the decision about deprecating `product.variant` field?

About handling the combined operators it's kind of simple, there is `and` between each operator, so in this case you will look for attributes with `PRODUCT_TYPE` with `name` == `Test1` or `name` == `Test` and with `slug` != `Slug1` and `slug` != `Slug2` and (`id` == `QXR0cmlidXRlOjIx` or `id` != `QXR0cmlidXRlOjI3` OR `name == "test`. So as a result you will get the `PRODUCT_TYPE` attributes in which `id` is in [ "QXR0cmlidXRlOjIx", "QXR0cmlidXRlOjI3"] and `name` is in `["Test1", "Test"]` and the attribute slug is different than `["Slug1", "Slug2"]`

**Comment by IKarbowiak** [comment]
> MHO, where should be PREVIEW_FEATURE. We want to have a possibility to improve it based on the feedback. In that case, we shouldn't immediately deprecate the filter fields. If we do that, we will have to recommend using where which will not be "fully stable" until we will decide to remove PREVIEW_FEATURE label.

We will sign the new filters as PREVIEW_FEATURE, for sure, but maybe you are right, that we shouldn't deprecate the current feature at the beginning.

**Comment by patrys** [comment]
@korycins The canonical way to fetch a variant is using `Query.productVariant`. You can fetch the related product from there.

Also, consider the following query to see why this filter does not belong as an embedded field:

```graphql
{
  products (first: 100, channel: "...") {
    edges {
      node {
        variant(sku: "STEVE") {
          id
        }
      }
    }
  }
}
```

**Comment by IKarbowiak** [comment]
Closing as most of the work has been done.
