### ISSUE TITLE
[RFC] Refactor sales price calculations in the checkout flow

### ISSUE THREAD

**Issue by fowczarek** [saleor/saleor#11887]
> #11887 Is split into parts:
> - **Refactor sales price calculations in the checkout flow(current ticket)**
> - Refactor Voucher price calculations in the checkout flow
> - Refactor Order discounts
> - Clean code related to calculations after price recalculation refactoring

## Problem
In the future, we want to add more complex solutions which will replace current Sales. To make it easier we decided to refactor the price calculations. 

## Basic terms:
1. Sale - Allows decreasing prices of products without any customer action. Could be applied to specific lines.
2. Voucher - Allows decreasing prices of products after customer attaches code to order. Could be applied to specific lines, the entire order/checkout, or shipping.  
3. Discounts - Vouchers and Sales
4. CheckoutDiscount/OrderDiscount - Objects store all information about discounts given for the entire order/checkout. 
5. CheckoutLineDiscount/OrderLineDiscount - Objects store all information about discounts given for the line. 
6. CheckoutShippingDiscount/OrderShippingDiscount -  Objects store all information about discounts given for the shipping. 
7. ObjectDiscounts - All discounts objects. (`CheckoutDiscount`, `OrderDiscount`, `CheckoutLineDiscount`, `OrderLineDiscount`, `CheckoutShippingDiscount`, and `OrderShippingDiscount`)

## General idea
We want to introduce objects like `CheckoutDiscount`, `CheckoutLineDiscount`, `CheckoutShippingDiscount`, and `OrderShippingDiscount` and reuse `OrderDiscount` and `OrderLineDiscount`.  Each `Checkout`, and `Order` could have multiple discounts from given types. 

All old discount-related fields should work in the same way. 
Deprecated fields in API:
- Checkout
  - discount
  - discountName
  - translatedDiscountName

## Price calculation flow
```mermaid
graph TD
  subgraph Scope of this task
 A[Calculate base prices on order/checkout - without discounts] -->|Fetch all Sales that could be applied| B[Create/Update ObjectDiscounts for Sales]
 end
 B --> |Fetch Voucher| C[Create ObjectDiscounts for Vouchers]
 C --> D[Recalculate new prices with line and shipping discount calculated]
 D --> F[Calculate taxes - Order/Checkout discount should be propagated]
 F --> G[Save recalculated price to Order/Checkout ]
```

Prices saved in checkout/order will be valid due to rules introduced [here.](https://docs.saleor.io/docs/3.x/developer/extending/apps/synchronous-webhooks/tax-webhooks#key-concepts)) 

## ObjectDisconts
All objects should have a relation to `Order`, or `Checkout`. `ObjectLineDiscount` should also have a relation to the given line. 

## Models 
```python
class DiscountType:
    VOUCHER = "voucher"
    MANUAL = "manual"
    SALE = "sale" 
    CHOICES = [(VOUCHER, "Voucher"), (MANUAL, "Manual"),(Sale, "Sale")]
    

class DiscountValueType:
    FIXED = "fixed"
    PERCENTAGE = "percentage"

    CHOICES = [
        (FIXED, "fixed"),
        (PERCENTAGE, "%"),
    ]


class BaseDiscount(models.Model):
    id = models.UUIDField(primary_key=True, editable=False, unique=True, default=uuid4)
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
    updated_at = models.DateTimeField(auto_now=True, db_index=True)
    type = models.CharField(
        max_length=10,
        choices=DiscountType.CHOICES,
        default=DiscountType.MANUAL,
    )
    value_type = models.CharField(
        max_length=10,
        choices=DiscountValueType.CHOICES,
        default=DiscountValueType.FIXED,
    )
    value = models.DecimalField(
        max_digits=settings.DEFAULT_MAX_DIGITS,
        decimal_places=settings.DEFAULT_DECIMAL_PLACES,
        default=Decimal("0.0"),
    )
    amount_value = models.DecimalField(
        max_digits=settings.DEFAULT_MAX_DIGITS,
        decimal_places=settings.DEFAULT_DECIMAL_PLACES,
        default=Decimal("0.0"),
    )
    amount = MoneyField(amount_field="amount_value", currency_field="currency")
    currency = models.CharField(
        max_length=settings.DEFAULT_CURRENCY_CODE_LENGTH,
    )
    name = models.CharField(max_length=255, null=True, blank=True)
    translated_name = models.CharField(max_length=255, null=True, blank=True)
    reason = models.TextField(blank=True, null=True)
    sale = models.ForeignKey(
        Sale,
        related_name="+",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )
    voucher = models.ForeignKey(
        Voucher, related_name="+", blank=True, null=True, on_delete=models.SET_NULL
    )

    class Meta:
        abstract = True
        

class CheckoutLineDiscount(BaseDiscount):
    line = models.ForeignKey(
        "checkout.CheckoutLine",
        blank=True,
        null=True,
        on_delete=models.CASCADE,
    )
```

## New Sale calculation flow
To provide the best Sale value for customers we introduce a new way of calculating the sale amounts. 
To calculate apply sales on checkout we use:
```mermaid
graph TD
A{{For each sale, that could be, applied at checkout. Calculate proper discounts amounts for lines}} -->|Fixed discount| B
B[Apply discount to the line total. The discount value should be limited by line_total]
A -->|Percentage discount| C
C[Use Algorithm 1 to calculate proper line discounts for percentage sales]
C --> D
B --> D
D[For each line, choose the best available discount and assign it to the checkout/order line]
```

**Algorithm 1** - Calculate discount values for a percentage sale:
```mermaid
graph TD
A[Calculate the total amount of lines qualified for the sale<br>remaining_total ]
A --> B
B[Calculate the total discount value:<br>remaining_discount = remaining_total * discount_value / 100]
B --> C
C[Chose first line]
C --> D
D[Calculate the discount for the selected line and round it to currency precision using half-up rounding.<br>line_discount = line_total * remaining_discount / remaining_total]
D --> E
E[Calculate remaining discount<br>remaining_discount = remaining_discount - line_discount]
E --> F
F[Calculate remaining total<br>remaining_total = remaining_total - line_total]
F --> G
G{{If next line exists}}
G -->|No| H
H[End]
G -->|Yes| I
I[Choos next line]
I --> D
```

## TODO:
- [x] Add models
- [x] Clear models (~1h)
- [x] Datamigrations (~6h)
- [x] Adjust migration to zero downtime policy (~4h)
- [x] Fetch all Sales that could be applied
- [x] Converting Salse -> ObjectDiscounts
- [x] Implement new calculation flow (~10h)
- [x] Adjust calculation flow to include new discounts objects (~2h)
- [x] Remove old sale calculation from price recalculation flow (~4h)
- [x] Make deprecated fields backward compatible (~3h)
- [x] Drop unused discounts argument 
- [x] Add test for fixed Sale is properly calculated for lines with quantity > 1
- [ ] In the migration guide & changelog describe how to get sales in the new flow(Plugins).

## To test:
- [x] Check price precision calculation(Apply 10% discount on 0.01 USD product with quantity > 10) 
- [x] Test checkout with overrode prices
- [x] Order create form checkout with new calculation flow should work in a similar way to the previous one
- [x] Backward compatibility of migrations
- [x] Check that all tax systems working correctly
    - [x] Without tax
    - [x] Flat rates
    - [x] Avalara
    - [x] Tax apps
