### ISSUE TITLE
[RFC] Refactor Voucher price calculations in checkout flow.

### ISSUE THREAD

**Issue by fowczarek** [saleor/saleor#12108]
> #11887 Is split into parts:
> - Refactor sales price calculations in the checkout flow
> - **Refactor Voucher price calculations in the checkout flow(current ticket)**
> - Refactor Order discounts
> - Clean code related to calculations after price recalculation refactoring

## Problem
In the future, we want to add more complex solutions which will replace current Sales. To make it easier we decided to refactor the price calculations related to sales and vouchers. 

## Basic terms:
1. Sale - Allows decreasing prices of products without any customer action. Could be applied to specific lines.
2. Voucher - Allows decreasing prices of products after customer attaches code to order. Could be applied to specific lines, the entire order/checkout, or shipping.  
3. Discounts - Vouchers and Sales
4. CheckoutDiscount/OrderDiscount - Objects store all information about discounts given for the entire order/checkout. 
5. CheckoutLineDiscount/OrderLineDiscount - Objects store all information about discounts given for the line. 
6. CheckoutShippingDiscount/OrderShippingDiscount -  Objects store all information about discounts given for the shipping. 
7. ObjectDiscounts - All discounts objects. (`CheckoutDiscount`, `OrderDiscount`, `CheckoutLineDiscount`, `OrderLineDiscount`, `CheckoutShippingDiscount`, and `OrderShippingDiscount`)
8. Tax System - Part of the Saleor responsible for tax calculations(Tax plugins, Tax apps, flat rates, no taxes). 

## General idea
We want to introduce objects like `CheckoutDiscount`, `CheckoutLineDiscount`, `CheckoutShippingDiscount`, and `OrderShippingDiscount` and reuse `OrderDiscount` and `OrderLineDiscount`.  Each `Checkout`, and `Order` could have multiple discounts from given types. 

All old discount-related fields should work in the same way. 
Deprecated fields in API:
- Checkout
  - discount
  - discountName
  - translatedDiscountName
  
## Price calculation flow
```mermaid
graph TD
 A[Calculate base prices on order/checkout - without discounts] -->|Fetch all Sales that could be applied| B[Create/Update ObjectDiscounts for Sales]
 B --> |Fetch Voucher| C[Create ObjectDiscounts for Vouchers]
 D[Recalculate new prices with line and shipping discount calculated]
  subgraph Scope of this task
 C --> D
 end
 D --> F[Calculate taxes - Order/Checkout discount should be propagated]
 F --> G[Save recalculated price to Order/Checkout ]
```

Prices saved in checkout/order will be valid due to rules introduced [here.](https://docs.saleor.io/docs/3.x/developer/extending/apps/synchronous-webhooks/tax-webhooks#key-concepts)) 

## ObjectDisconts
All objects should have a relation to `Order`, or `Checkout`. `ObjectLineDiscount` should also have a relation to the given line. 

## Models 
```python
class DiscountType:
    VOUCHER = "voucher"
    MANUAL = "manual"
    SALE = "sale" 
    CHOICES = [(VOUCHER, "Voucher"), (MANUAL, "Manual"),(Sale, "Sale")]
    

class DiscountValueType:
    FIXED = "fixed"
    PERCENTAGE = "percentage"

    CHOICES = [
        (FIXED, "fixed"),
        (PERCENTAGE, "%"),
    ]


class BaseDiscount(models.Model):
    id = models.UUIDField(primary_key=True, editable=False, unique=True, default=uuid4)
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
    updated_at = models.DateTimeField(auto_now=True, db_index=True)
    type = models.CharField(
        max_length=10,
        choices=DiscountType.CHOICES,
        default=DiscountType.MANUAL,
    )
    value_type = models.CharField(
        max_length=10,
        choices=DiscountValueType.CHOICES,
        default=DiscountValueType.FIXED,
    )
    value = models.DecimalField(
        max_digits=settings.DEFAULT_MAX_DIGITS,
        decimal_places=settings.DEFAULT_DECIMAL_PLACES,
        default=Decimal("0.0"),
    )
    amount_value = models.DecimalField(
        max_digits=settings.DEFAULT_MAX_DIGITS,
        decimal_places=settings.DEFAULT_DECIMAL_PLACES,
        default=Decimal("0.0"),
    )
    amount = MoneyField(amount_field="amount_value", currency_field="currency")
    currency = models.CharField(
        max_length=settings.DEFAULT_CURRENCY_CODE_LENGTH,
    )
    name = models.CharField(max_length=255, null=True, blank=True)
    translated_name = models.CharField(max_length=255, null=True, blank=True)
    reason = models.TextField(blank=True, null=True)
    sale = models.ForeignKey(
        Sale,
        related_name="+",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )
    voucher = models.ForeignKey(
        Voucher, related_name="+", blank=True, null=True, on_delete=models.SET_NULL
    )

    class Meta:
        abstract = True


class CheckoutDiscount(BaseDiscount):
    checkout = models.ForeignKey(
        "checkout.Checkout",
        related_name="discounts",
        blank=True,
        null=True,
        on_delete=models.CASCADE,
    )

class CheckoutShippingDiscount(BaseDiscount):
    checkout = models.ForeignKey(
        "checkout.Checkout",
        related_name="shipping_discounts",
        blank=True,
        null=True,
        on_delete=models.CASCADE,
    )
```

## New percentage voucher calculation flow
To provide the best Voucher value for customers we introduce a new way of calculating the voucher discount amounts.
```mermaid
graph TD
A[Calculate the total amount of lines qualified for the voucher<br>remaining_total ]
A --> B
B[Calculate the total discount value:<br>remaining_discount = remaining_total * discount_value / 100]
B --> C
C[Chose first line]
C --> D
D[Calculate the discount for the selected line and round it to currency precision using half-up rounding.<br>line_discount = line_total * remaining_discount / remaining_total]
D --> E
E[Calculate remaining discount<br>remaining_discount = remaining_discount - line_discount]
E --> F
F[Calculate remaining total<br>remaining_total = remaining_total - line_total]
F --> G
G{{If next line exists}}
G -->|No| H
H[End]
G -->|Yes| I
I[Choos next line]
I --> D
```

## TODO:
- [ ] Add models
- [ ] Datamigrations
- [ ] Adjust migration to zero downtime policy.
- [ ]  Generate discount objects for:
   - [ ] Shipping Voucher
   - [ ] Specific Product Voucher
   - [ ] Entire Order Voucher
   - [ ] Handle apply once per order flag
- [ ] Update lines and shipping prices (⚠️ Entire order discount should be propagated by Tax System) 
- [ ] Refactor add a voucher to checkout mutation.
- [ ] Adjust order to create a flow to new calculations
    - [ ] `orderCreateFromCheckout` mutation
    - [ ] `checkoutComplete` mutation
- [ ] Voucher calculation doesn't validate the possibility to apply voucher. This should be validated in please when we modify checkout:
     - [ ] Add promo code mutation
     - [ ] Change customer attached to checkout
     - [ ] Checkout line CRUD mutations
     - [ ] Checkout complete
- [ ] Make deprecated fields backward compatible

## To test:
- [ ] Check price precision calculation(Apply 10% discount on 0.01 USD product with quantity > 10) 
- [ ] Test checkout with overrode prices
- [ ] Order create form checkout with new calculation flow should work in a similar way to the previous one
- [ ] Check that all tax systems correctly apply CheckoutDiscount
    - [ ] Without tax
    - [ ] Flat rates
    - [ ] Avalara
    - [ ] Tax apps
