### ISSUE TITLE
Add webhook: order_refunded, order_fully_refunded, order_paid

### ISSUE THREAD

**Issue by korycins** [saleor/saleor#12495]
## Problem
The current order webhooks do not allow you to track (partially) refunded or partially paid orders. These webhooks are crucial for building a notification app. Without them, we are unable to notify the user after processing the charge or refund request.

Add new webhooks:
- ORDER_REFUNDED
- ORDER_FULLY_REFUNDED
- ORDER_PAID (we already have event ORDER_FULLY_PAID)

## 1. General Assumptions

The new webhooks can be triggered when something changes in the order's amount. The following events should be triggered:

- `ORDER_REFUNDED` should be triggered when a refund occurs for the order.
- `ORDER_FULLY_REFUNDED` should be called when the order is fully refunded.
- `ORDER_PAID` should be called when payment for the order is charged.

The webhooks should be called for `transactionAPI` and for `paymentsAPI`.

The same permission as for ORDER_FULLY_PAID will be required.

### Acceptance Criteria
- [ ] New webhooks now have their own subscription types.
- [ ]  Payments:
    - [ ] The `ORDER_PAID` event should be triggered when an order is paid.
    - [ ]  Refunding an order's payment should trigger the `ORDER_REFUNDED` event.
    - [ ] When an order is fully refunded, the `ORDER_FULLY_REFUNDED` event should be triggered.
    - [ ] Any existing mutations that operate on payments, such as `orderCapture`, `orderRefund`, `orderFulfillmentRefundProducts`, and `orderFulfillmentReturnProducts`, should trigger the appropriate event.
- [ ] Transactions:
    - [ ] The `ORDER_PAID` event should be triggered when a transaction with a `chargedAmount` of `X` is assigned to the order via the `transactionCreate` method.
    - [ ] The `ORDER_PAID` event should be triggered when a transaction with a `chargedAmount` of `X` is updated via the `transactionUpdate`, `transactionEventReport`, or response to the sync webhook methods.
    - [ ] The `ORDER_REFUNDED` event should be triggered when a transaction with a `refundedAmount` of `X` is assigned to the order via the `transactionCreate` method.
    - [ ] The `ORDER_REFUNDED` event should be triggered when a transaction with a `refundedAmount` of `X` is updated via the `transactionUpdate`, `transactionEventReport`, or response to the sync webhook methods.
    - [ ] The `ORDER_REFUNDED` or `ORDER_PAID` event should be triggered when an order is created and the amount of `refundedAmount:X` or `chargedAmount:X` is not equal to 0.
    - [ ] The `ORDER_FULLY_REFUNDED` event should be triggered when an order is fully refunded via the `transactionCreate`, `transactionUpdate`, `transactionEventReport`, or response to the sync webhook methods.

### Mutations

```

```

### Types

```

```

## 4. UML diagrams

```mermaid

```

## 5. To Do list

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

## 6. To Test

- [ ]
- [ ]
