### ISSUE TITLE
Delete expired orders

### ISSUE THREAD

**Issue by korycins** [saleor/saleor#12544]
## Problem

When using the mutation `orderCreateFromCheckout`, there is a possibility that created orders will not have any transaction or payment attached to them (first order then payment flow). To address this issue, we control the time after which all orders without payment will expire using `channel.expireOrdersAfter`. In issue #11351, we are introducing the possibility to anonymize expired orders. However, we also need a flow for deleting these expired orders.

Our proposition is to create a task that will delete expired orders after a certain amount of time. Specifically, we will delete all expired orders older than the TTL.

---

## 1. General Assumptions

We are introducing a new Celery task that will be responsible for deleting all expired orders that have exceeded the provided TTL (time-to-live).

To ensure that the Celery task can handle high loads, we can use the implementation from issue #11257 as an example. The Celery beat should trigger the task once per day.

Staff users will control the TTL for deleting expired orders through channel settings, similar to the one used for controlling expiring orders. They will be able to provide a value in days (a new scalar), within a range defined by Saleor. The proposed range is from 0 to 120 days, with a default value of 60 days.

For example, if an order expires on 2023-Jan-01 00:00:00 with the default value, it will be deleted 60 days later.

### Acceptance Criteria

- [ ]  A staff user can set a Time To Live (TTL) for deleting the orders.
- [ ]  Settings can be set by a user with permissions: MANAGE_ORDERS or MANAGE_CHANNELS
- [ ]  Once the TTL has expired, the expired  order should be removed.

## 2. API changes

```graphql
"""
The `Day` scalar type represents number of days by integer value.
"""
scalar Day

input OrderSettingsInput @doc(category: "Orders") {

  """Delete expired orders time in days. Default 60. Enter 0 or null to disable. """
  deleteExpiredOrdersAfter: Day
}

type Channel {
   ...
   deleteExpiredOrdersAfter: Day!
}
```

## 3. Database changes

```python
class Channel(models.Model):
    ...
    delete_expired_orders_after = models.DurationField(default=None, null=True, blank=True)
```

```python
class Order(models.Model):
    ...
    expired_at = models.DateTimeField(null=True, blank=True)
```

## 4. To Do list

```[tasklist]
### Tasks
- [x] Add a Celery task to delete expired orders.
- [x] Configure a Celery beat to trigger the implemented task.
- [x] Extend the `Channel` input to accept a new value to control the time-to-live (TTL) of deletion.
- [x] Provide a zero-downtime migration.
- [ ] https://github.com/saleor/saleor/issues/12774
```
