### ISSUE TITLE
Move flag ENABLE_ACCOUNT_CONFIRMATION_BY_EMAIL to site settings

### ISSUE THREAD

**Issue by timuric** [saleor/saleor#12762]
## Problem
Dashboard users should be able to disable email confirmation settings for newly registered users instead of relying on ENABLE_ACCOUNT_CONFIRMATION_BY_EMAIL env variable. Setting sh

### Acceptance Criteria

- [ ]  Users should have permissions MANAGE_SETTINGS to control this

- [ ] Support for old versions is not necessary.

### Mutations

```

```

### Types

```

```

## 4. UML diagrams

```mermaid

```

## 5. To Do list

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

## 6. To Test

- [ ]
- [ ]
