### ISSUE TITLE
[RFC] Promotion rules

### ISSUE THREAD

**Issue by IKarbowiak** [saleor/saleor#12794]
## Problem

Introduce the promotion rules that allow applying discounts based on certain conditions. 
Conditional discounts are based on basket predicates such as Product, Variant, Collection, and Category.
Later also Attributes and Quantity. 

The promotion rule will replace the current `Sale`.

## 1. General Assumptions
- The promotion rule functionality must cover all sale functionalities:
  - Allow defining conditions based on Product, Variant, Collection, and Category.
  - Allow defining percentage or fixed discount
  - Allow defining discount value per channel
  - Allow setting start and end date
  - Support metadata
- Migrate old sales to new promotions, drop old sale model
- Ensure zero downtime support
- The `promotion rule` will have two targets: `Catalogue` or `Checkout and order. `Catalogue` promotion rule will correspond to our current sales.
- The `promotion rule` will have predicates and a reward.
- The rule will have only one reward
- The rule could have multiple predicates.
- The rule will be defined per `currency`.
- The channels that support chosen currency could be assigned to the rule
- The rule could have multiple channels
- There will be an option for a multi-currency rule. In such case, currency bases predicates and rewards will be forbidden.
- The predicated will be on `catalogues` and on `checkout or order`.
- The reward will be applied only when predicated will be fulfilled.
- There will be an option to also apply the reward predicates that will define which items from the cart should be discounted.
- The reward predicate could be defined only for `SPECIFIC_PRODUCT_DISCOUNT` or `EACH_X_ITEM_FREE` reward type.
- There will be an option to define the list of available gifts. The option will be available only when the `GIFT` reward type will be chosen.
- There will be the option to define the availability predicates that define when the sale should be available

### Examples
**Predicates dictionary:**
- **cataloguePredicate** - defines the conditions for catalogue discounts that will be applied on products view
- **checkoutAndOrderPredicate** - defines the condition that must be fulfilled to get the reward on the checkout/draft order level
- **rewardPredicate** - to be used with `SPECIFIC_PRODUCT_DISCOUNT` and `EACH_X_ITEM_FREE`, allows defining which items should be discounted
- **availabilityPredicate** - defines the conditions when the promotion should be applicable

#### Promotion availability
- Available every Wednesday  
  ```json
  {
   "promotion": {
    "availabilityPredicate": {
    	"weekDay": ["WEDNESDAY"]
    },
   }
  }
  ```
- Available on Sunday, and Saturday every 4 weeks and on Friday every 2 weeks
  ```json
  {
   "promotion": {
    "availabilityPredicate": {
       "AND": [
        {
    	  "weekDay": ["SATURDAY", "SUNDAY"],
    	  "weeksFrequency": 4
        },
        {
    	  "weekDay": ["FRIDAY"],
    	  "weeksFrequency": 2
        }
       ]
    },
   }
  }
  ```
    
#### Catalogue discounts
- 10% discount on collection X
 
```json
  {
   "promotionRule": {
    "cataloguePredicate": {
      "collectionPredicate": {
        "ids": ["Q29sbGVjdGlvbjox"]
      }
    },
    "rewardValueType": "PERCENTAGE",
    "rewardValue": 10
   }
  }
 ```

- 10% discount on category X
 
```json
  {
   "promotionRule": {
    "cataloguePredicate": {
      "categoryPredicate": {
        "ids": ["Q29sbGVjdGlvbjox"]
      }
    },
    "rewardValueType": "PERCENTAGE",
    "rewardValue": 10
   }
  }
 ```

- 10% discount on variant X
 
```json
  {
   "promotionRule": {
    "cataloguePredicate": {
      "variantPredicate": {
        "ids": ["Q29sbGVjdGlvbjox"]
      }
    },
    "rewardValueType": "PERCENTAGE",
    "rewardValue": 10
   }
  }
 ```

- 10% discount on product X
 
```json
  {
   "promotionRule": {
    "cataloguePredicate": {
      "productPredicate": {
        "ids": ["Q29sbGVjdGlvbjox"]
      }
    },
    "rewardValueType": "PERCENTAGE",
    "rewardValue": 10
   }
  }
 ```

 - $10 discount on collection X or category X or variant X or product X
```json
  {
   "promotionRule": {
    "cataloguePredicate": {
       "OR": [
         {
           "collectionPredicate": {
              "ids": ["Q2F0ZWdvcnk6OA=="]
           },
         },
         {
           "categoryPredicate": {
              "ids": ["Q2F0ZWdvcnk6OA=="]
           }
         },
         {
           "variantPredicate": {
              "ids": ["Q2F0ZWdvcnk6OA=="]
           }
         },
         {
           "productPredicate": {
              "ids": ["Q2F0ZWdvcnk6OA=="]
           }
         }
       ]
    },
    "rewardValueType": "FIXED",
    "rewardValue": 10
   }
  }
```
 - 5% discount on products with cotton attribute
```json
{
  "promotionRule": {
    "cataloguePredicate": {
      "productPredicate": {
       "attributes": {
        "values": {
          "slug": {
             "eq": "cotton"
              }
          }
        }
      }
    },
    "rewardValueType": "PERCENTAGE",
    "rewardValue": 5
  }
}
```
- 10% discount on all products except category X

```json
  {
   "promotionRule": {
    "cataloguePredicate": {
      "categoryPredicate": {
           "id":{ "notIn": ["Q29sbGVjdGlvbjox"] }
     },
    "rewardValueType": "PERCENTAGE",
    "rewardValue": 10
   }
  }
 ```
#### Checkout and Order discounts
- Free shipping when you spend $50
```json
{
 "promotionRule": {
  "checkoutAndOrderPredicate": {
   "discountedObjectPredicate": {
    "subtotalPrice": {
    	"range": {
    	  "gte": 50
    	}
    }
   }
  },
  "rewardType": "SHIPPING_DISCOUNT"
  "rewardValueType": "PERCENTAGE",
  "rewardValue": 100
 }
}
```
- Free shipping when you spend $50 and the order/checkout is made from US

```json
  {
   "promotionRule": {
    "checkoutAndOrderPredicate": {
    	"discountedObjectPredicate": {
          "country": {
    	      "eq": "US"
          }
    	}
    },
    "rewardType": "SHIPPING_DISCOUNT",
    "rewardValueType": "PERCENTAGE",
    "rewardValue": 100
   }
  }
```
- 20% discount on subtotal when you spend at least $100
```json
{
 "promotionRule": {
  "checkoutAndOrderPredicate": {
   "discountedObjectPredicate": {
    "subtotalPrice": {
    	"range": {
    	  "gte": 100
    	}
    }
   }
  },
  "rewardType": "SUBTOTAL_DISCOUNT",
  "rewardValueType": "PERCENTAGE",
  "rewardValue": 20
 }
}
```
- When you spend $25 you will get 20% on products from the collection with the name X and from category Y

> 💡 rewardPredicate can be set only when `SPECIFIC_PRODUCT_DISCOUNT` or `EACH_X_ITEM_FREE` is chosen.

```json
{
"promotionRule": {
"checkoutAndOrderPredicate": {
 "discountedObjectPredicate": {
  "subtotalPrice": {
   "range": {
    "gte": 25
   }
  }
 }
},
"rewardPredicate": {
 "AND": [
  {
   "collectionPredicate": {
    "name": {
    	"eq": "X"
    }
   }
  },
  {
   "categoryPredicate": {
    "ids": ["Q2F0ZWdvcnk6OA=="]
    }
   }
 ]
},
"rewardType": "SPECIFIC_PRODUCT_DISCOUNT",
"rewardValueType": "PERCENTAGE",
"rewardValue": 20
}
}
```
- 50% discount for staff users
```json
{
 "promotionRule": {
  "checkoutAndOrderPredicate": {
   "discountedObjectPredicate": {
    "userPredicate": {
    	"isStaff": true
    }
   }
  },
  "rewardType": "SUBTOTAL_DISCOUNT",
  "rewardValueType": "PERCENTAGE",
  "rewardValue": 50
 }
}
```
- Buy any 3 products from the category Shirt for $100
```json
{
  "promotionRule": {
    "checkoutAndOrderPredicate": {
      "AND": [
        {
          "discountedLineObjectPredicate": {
            "quantity": {
              "range": {
                "gte": 3
              }
            }
          }
        },
        {
          "discountedLineObjectPredicate": {
            "cataloguePredicate": {
              "categoryPredicate": {
                "name": {
                  "eq": "Shirt"
                }
              }
            }
          }
        }
      ]
    },
    "rewardValueType": "FIXED_PRICE",
    "discountValueType": "FIXED",
    "rewardValue": 100
  }
}
```
- Buy any 3 products with Cotton or Silk attribute for $100
```json
{
  "promotionRule": {
    "checkoutAndOrderPredicate": {
      "AND": [
        {
         "discountedLineObjectPredicate": {
          "quantity": {
           "range": {
    	     "gte": 3
           }
          }
         }
        },
        {
        "discountedLineObjectPredicate": {
         "cataloguePredicate": {
          "productPredicate": {
            "attribute": {
              "values": {
    	        "oneOf": ["cotton", "silk"]
              }
             }
          }
          }
         }
        }
      ]
    },
    "rewardValueType": "FIXED_PRICE",
    "discountValueType": "FIXED",
    "rewardValue": 100
  }
}
```
- Buy 2 cups get a gift for free
>     💡 Gift defines a list of available gifts that the user can choose from. When the list has only one item it will be added automatically
```json
{
"promotionRule": {
"checkoutAndOrderPredicate": {
 "AND": [
  {
   "discountedLineObjectPredicate": {
    "quantity": {
    	"range": {
    	  "gte": 2
    	}
    }
   }
  },
  {
   "discountedLineObjectPredicate": {
    "cataloguePredicate": {
    	"productPredicate": {
    	  "name": {
    		  "eq": "Cup"
    	  }
        }
    }
   }
  },
 ]
}
"rewardType": "GIFT",
"rewardValueType": null,
"rewardValue": 0,
"gift": ["XYZ1", "XYZ2", "XYZ3"]
}
}
```
- Buy 2 shirts get 1 free
> 💡 `everyXItem` is required when `EACH_X_ITEM` reward type is chosen
```json
{
"promotionRule": {
  "rewardPredicate": {
    "productPredicate": {
      "name": {
        "eq": "Shirt"
      }
    }
  },
  "rewardType": "EACH_X_ITEM",
  "rewardValueType": "PERCENTAGE",
  "rewardValue": 100,
  "everyXItem": 3,
  "gift": null
  }
}
```

### Acceptance Criteria

- [ ] Support for old versions: the old sales should work as before
- [ ] The Promotion rules support all functionalities as old sales

### Types

```graphql
type Promotion implements Node & ObjectWithMetadata @doc(category: "Discounts") {
  id: ID!
  name: String!
  description: String
  isStackable: Boolean!
  startDate: DateTime!
  endDate: DateTime
  createdAt: DateTime!
  updatedAt: DateTime!
  rules: [PromotionRule!]!
  availabilityPredicate: AvailabilityPredicate
  privateMetadata: [MetadataItem!]!
  privateMetafield(key: String!): String
  privateMetafields(keys: [String!]): Metadata
  metadata: [MetadataItem!]!
  metafield(key: String!): String
  metafields(keys: [String!]): Metadata
}

type PromotionRule implements Node @doc(category: "Discounts"){
  id: ID!
  name: String!
  description: JSON
  channels: [ID!]
  cataloguePredicate: CataloguePredicate
  checkoutAndOrderPredicate: CheckoutAndOrderPredicate
  rewardType: RewardTypeEnum
  rewardPredicate: JSON
  rewardValueType: RewardValueTypeEnum!
  rewardValue: PositiveDecimal
  everyXItem: Int
  gift: [ID!]
}

type AvailabilityPredicate @doc(category: "Discounts"){
  weekDay: [WeekDayEnum!]
  weeksFrequency: Int
  AND: [AvailabilityPredicate]
  OR: [AvailabilityPredicate]
}

type CataloguePredicate @doc(category: "Products"){
    predicate: CatalogueObjectsPredicate
    AND: [CataloguePredicate]
    OR: [CataloguePredicate]   
}

union CatalogueObjectsPredicate = ProducPredicate | ProducVariantPredicate | CategoryPredicate | CollectionPredicate

type ProducPredicate @doc(category: "Products"){
  ids: [ID!]
  name: StringFilterInput
  slug: StringFilterInput
  seoTitle: StringFilterInput
  attributes: [AttributeInput!]
  createdAt: DateTimeFilterInput
  updatedAt: DateTimeFilterInput
  productType: IdFilterInput
  chargeTaxes: Boolean
  minimalPrice: PriceFilterInput
}

type ProducVariantPredicate @doc(category: "Products"){
  ids: [ID!]
  name: StringFilterInput
  sku: StringFilterInput
  quantityAvailable: IntFilterInput
  createdAt: DateTimeFilterInput
  updatedAt: DateTimeFilterInput
  externalReference: StringFilterInput
  isPreorder: boolean
  price: PriceFilterInput
  priceUndiscounted: PriceFilterInput
}

type CategoryPredicate @doc(category: "Products"){
  ids: [ID!]
  name: StringFilterInput
  slug: StringFilterInput
}

type CollectionPredicate @doc(category: "Products"){
  ids: [ID!]
  name: StringFilterInput
  slug: StringFilterInput
}

type CheckoutAndOrderPredicate @doc(category: "Discounts"){
  discountedObjectPredicate: DiscountedObjectPredicate
  discountedLineObjectPredicate: DiscountedLineObjectPredicate
  AND: [DiscountedObjectPredicate]
  OR: [DiscountedObjectPredicate]   
}

type DiscountedObjectPredicate @doc(category: "Discounts"){
  country: StringFilterInput
  totalQuantity: DecimalFilterInput
  subtotalPrice: DecimalFilterInput
  totalPrice: DecimalFilterInput
  createdAt: DateTimeFilterInput
  userPredicate: UserPredicate
}

type UserPredicate @doc(category: "Users"){
  ids: [ID!]
  isStaff: Boolean
  isActive: Boolean
  email: StringFilterInput
  firstName: StringFilterInput
  lastName: StringFilterInput
  dateJoined: DateTimeFilterInput
}

type DiscountedLineObjectPredicate @doc(category: "Discounts"){
  quantity: IntFilterInput
  totalPrice: DecimalFilterInput
  unitPrice: DecimalFilterInput
  cataloguePredicate: CatalogueObjectsPredicate
}

enum WeekDayEnum @doc(category: "Discounts") {
  MONDAY
  THURSDAY
  WEDNESDAY
  THURSDAY
  FRIDAY
  SUNDAY
  SATURDAY
}

enum RewardTypeEnum @doc(category: "Discounts") {
  SHIPPING_DISCOUNT
  SPECIFIC_PRODUCT_DISCOUNT
  SUBTOTAL_DISCOUNT
  GIFT
  FIXED_PRICE
  EACH_X_ITEM
}

enum RewardValueTypeEnum @doc(category: "Discounts") {
  FIXED
  PERCENTAGE
}
```

### Mutations

```

```

## 4. UML diagrams

```mermaid
classDiagram
    Promotion -- PromotionRule
    PromotionRule -- CataloguePredicate
    PromotionRule -- CheckoutAndOrderPredicate
    PromotionRule -- Channel
    Promotion -- AvailabilityPredicate
    class Promotion{
        name: String
        description: String
        startDate: DateTime
        endDate: DateTime
        availabilityPredicate: AvailabilityPredicate
        isStackable: Boolean #postMVP
    }
    class PromotionRule{
        name: String
        description: String
        cataloguePredicate: CataloguePredicate
        checkoutAndOrderPredicate: CheckoutAndOrderPredicate
        rewardType: RewardTypeEnum
        rewardPredicate: CataloguePredicate
        rewardValueType: RewardValueTypeEnum!
        rewardValue: PositiveDecimal
        gift: [ID!]
    }

    class CataloguePredicate{
        predicate: CatalogueObjectsPredicate
        AND: [CataloguePredicate]
        OR: [CataloguePredicate]   
    }

    class CheckoutAndOrderPredicate{
        discountedObjectPredicate: DiscountedObjectPredicate
        discountedLineObjectPredicate: DiscountedLineObjectPredicate
        AND: [DiscountedObjectPredicate]
        OR: [DiscountedObjectPredicate]   
    }

    class CatalogueObjectPredicate{
        <<union>>
        ProducPredicate
        ProductVariantPredicate
        CategoryPredicate
        CollectionPredicate
    }

    class DiscountedObjectPredicate{
        country: StringFilterInput
        totalQuantity: DecimalFilterInput
        subtotalPrice: DecimalFilterInput
        totalPrice: DecimalFilterInput
        createdAt: DateTimeFilterInput
        userPredicate: UserPredicate
    }

    class UserPredicate{
        ids: [ID!]
        isStaff: Boolean
        isActive: Boolean
        email: StringFilterInput
        firstName: StringFilterInput
        lastName: StringFilterInput
        dateJoined: DateTimeFilterInput
    }

    class DiscountedLineObjectPredicate{
        quantity: IntFilterInput
        totalPrice: DecimalFilterInput
        unitPrice: DecimalFilterInput
        cataloguePredicate: CatalogueObjectsPredicate
    }

    class AvailabilityPredicate{
        weekDay: [WeekDayEnum!]
        weeksFrequency: Int
        AND: [AvailabilityPredicate]
        OR: [AvailabilityPredicate]
    }

    class ProducPredicate{
        ids: [ID!]
        name: StringFilterInput
        slug: StringFilterInput
        seoTitle: StringFilterInput
        attributes: [AttributeInput!]
        createdAt: DateTimeFilterInput
        updatedAt: DateTimeFilterInput
        productType: IdFilterInput
        chargeTaxes: Boolean
        minimalPrice: PriceFilterInput
    }

    class ProducVariantPredicate{
        ids: [ID!]
        name: StringFilterInput
        sku: StringFilterInput
        quantityAvailable: IntFilterInput
        createdAt: DateTimeFilterInput
        updatedAt: DateTimeFilterInput
        externalReference: StringFilterInput
        isPreorder: boolean
        price: PriceFilterInput
        priceUndiscounted: PriceFilterInput
    }

    class CategoryPredicate{
        ids: [ID!]
        name: StringFilterInput
        slug: StringFilterInput
    }

    class CollectionPredicate{
        ids: [ID!]
        name: StringFilterInput
        slug: StringFilterInput
    }

    class RewardTypeEnum{
        <<enumeration>>
        SHIPPING_DISCOUNT
        SPECIFIC_PRODUCT_DISCOUNT
        SUBTOTAL_DISCOUNT
        GIFT
        FIXED_PRICE
        EACH_X_ITEM
    }

    class RewardValueTypeEnum{
        <<enumeration>>
        FIXED
        PERCENTAGE
    }
```

## 5. To Do list

```[tasklist]
### Tasks
- [ ] https://github.com/saleor/saleor/issues/12539
- [ ] https://github.com/saleor/saleor/issues/12889 
- [ ] https://github.com/saleor/saleor/issues/12909
- [ ] https://github.com/saleor/saleor/issues/12910
- [ ] https://github.com/saleor/saleor/issues/12911
- [ ] https://github.com/saleor/saleor/issues/12912
- [ ] https://github.com/saleor/saleor/issues/12913
- [ ] https://github.com/saleor/saleor/issues/12925
- [ ] https://github.com/saleor/saleor/issues/13332
```

**Comment by senneclaeskens** [comment]
Hello,

> Later also Attributes and Quantity.

Does this mean it's not included in this phase and will only be available later on? It's a core feature for one of the solutions I'm currently designing.

Thanks!

**Comment by IKarbowiak** [comment]
Hi @senneclaeskens,

Our current roadmap for promotions includes only primary conditions for catalogue predicates. More advanced options will be available on order and checkout levels, and the plan consists of defining the conditions based on item quantity.

**Comment by IKarbowiak** [comment]
Closing as the rest of the implementation is postponed for now.
