### ISSUE TITLE
Include lines in refund requests

### ISSUE THREAD

**Issue by korycins** [saleor/saleor#12831]
## Problem
App needs to know which order lines & their quantities are refunding as this is required by some payment methods. Saleor needs to provide the app with the info about the lines that the user wants to refund.
Issue reported in https://github.com/saleor/saleor/issues/12382

---

## 1. General Assumptions

We will extend the OrderGrantedRefund to contain details about specific lines related to this action. We also include a flag for determining if shipping was also refunded. The granted refund mutation's inputs will allow to provide these data. We will add a new mutation for triggering the refund based on the granted refund. The webhook for refund action will receive a new field for granted refund.

`amount` field for grantedRefund is converted from REQUIRED to OPTIONAL. Based on the lines, `amount` can be calculated automatically by Saleor. `GrantedRefund` functionality is PREVIEW_FEATURE. 

### Acceptance Criteria

- [ ] Existing refund works as an expected
- [ ] The granted refund mutations allow adding lines and quantities
- [ ] The granted refund mutation allows setting a flag that determines the shipping refund
- [ ] The granted refund with lines cannot exceed the quantity bigger than available. availableQuantity= orderLine.quantity - sum(quantity-from-all-granted-refund-lines)
- [ ] The lines assigned to the granted refund can be fetched from the API
- [ ] The flag for refunding shipping can be fetched from the GrantedRefund type.
- [ ] New mutation allows triggering the refund action for the transaction by taking the grantedRefund id.
- [ ] New mutation requires permission HANDLE_PAYMENTS
- [ ] Webhook subscription `TransactionRefundRequested` contains details related to the granted refund assigned to this action (in a case when called with a new mutation). If called by `transactionRequestAction`, this field should be empty

#### Added
```graphql
enum TransactionRequestRefundForGrantedRefundErrorCode @doc(category: "Payments") {
  INVALID
  GRAPHQL_ERROR
  NOT_FOUND
}

type TransactionRequestRefundForGrantedRefundError @doc(category: "Payments") {
  """
  Name of a field that caused the error. A value of `null` indicates that the error isn't associated with a particular field.
  """
  field: String

  """The error message."""
  message: String

  """The error code."""
  code: TransactionRequestRefundForGrantedRefundErrorCode!
}

type TransactionRequestRefundForGrantedRefund {
  transactions: TransactionItem
  errors: [TransactionRequestRefundForGrantedRefundError!]!
}

""" HANDLE_PAYMENTS required """
transactionRequestRefundForGrantedRefund(
    """The field specifies the ID of the transaction for which a refund request
    will be triggered.
    """
    id: ID!

    """ID of the granted refund"""
    grantedRefundId: ID!
    
  ): TransactionRequestRefundForGrantedRefund
```

#### Updated

```graphql
"""An enumeration."""
enum OrderGrantRefundCreateLineErrorCode {
  GRAPHQL_ERROR
  NOT_FOUND
  QUANTITY_GREATER_THAN_AVAILABLE
}

type OrderGrantRefundCreateLineError {
  """
  Name of a field that caused the error. A value of `null` indicates that the error isn't associated with a particular field.
  """
  field: String

  """The error message."""
  message: String

  """The error code."""
  code: OrderGrantRefundCreateLineErrorCode!

  """The ID of the line related to the error."""
  lineId: ID!
}

type OrderGrantRefundCreateError @doc(category: "Orders") {
  """
  Name of a field that caused the error. A value of `null` indicates that the error isn't associated with a particular field.
  """
  field: String

  """The error message."""
  message: String

  """The error code."""
  code: OrderGrantRefundCreateErrorCode!

  """
  List of lines which cause the error.
  
  Added in Saleor 3.14.
  """
  lines: [OrderGrantRefundCreateLineError!]
}

input OrderGrantRefundCreateLineInput @doc(category: "Orders") {
  """The ID of the order line."""
  id: ID!

  """The quantity of line items to be marked to refund."""
  quantity: Int!

  """Reason of the granted refund."""
  reason: String
}

input OrderGrantRefundCreateInput @doc(category: "Orders") {
  """
  Amount of the granted refund. If not provided, the amount will be calculated automatically based on provided `lines` and `grantRefundForShipping`.
  """
  amount: Decimal

  """Reason of the granted refund."""
  reason: String

  """
  Lines to assign to granted refund.
  
  Added in Saleor 3.14.
  """
  lines: [OrderGrantRefundCreateLineInput!]

  """
  Determine if granted refund should include shipping costs.
  
  Added in Saleor 3.14.
  """
  grantRefundForShipping: Boolean
}

input OrderGrantRefundUpdateLineInput @doc(category: "Orders") {
  """The ID of the order line."""
  id: ID!

  """The quantity of line items to be marked to refund."""
  quantity: Int!
  
  """Reason of the granted refund."""
  reason: String
}

input OrderGrantRefundUpdateInput @doc(category: "Orders") {
  """
  Amount of the granted refund. if not provided and `addLines` or `removeLines` or `grantRefundForShipping` is provided, amount will be calculated automatically.
  """
  amount: Decimal

  """Reason of the granted refund."""
  reason: String

  """
  Lines to assign to granted refund.
  
  Added in Saleor 3.14.
  """
  addLines: [OrderGrantRefundUpdateLineAddInput!]

  """
  Lines to remove from granted refund.
  
  Added in Saleor 3.14.
  """
  removeLines: [ID!]

  """
  Determine if granted refund should include shipping costs.
  
  Added in Saleor 3.14.
  """
  grantRefundForShipping: Boolean
}

type OrderGrantRefundUpdateError @doc(category: "Orders") {
  """
  Name of a field that caused the error. A value of `null` indicates that the error isn't associated with a particular field.
  """
  field: String

  """The error message."""
  message: String

  """The error code."""
  code: OrderGrantRefundUpdateErrorCode!

  """
  List of lines to add which cause the error.
  
  Added in Saleor 3.14.
  """
  addLines: [OrderGrantRefundUpdateLineError!]

  """
  List of lines to remove which cause the error.
  
  Added in Saleor 3.14.
  """
  removeLines: [OrderGrantRefundUpdateLineError!]
}

type OrderGrantRefundUpdateLineError {
  """
  Name of a field that caused the error. A value of `null` indicates that the error isn't associated with a particular field.
  """
  field: String

  """The error message."""
  message: String

  """The error code."""
  code: OrderGrantRefundUpdateLineErrorCode!

  """The ID of the line related to the error."""
  lineId: ID!
}

"""An enumeration."""
enum OrderGrantRefundUpdateLineErrorCode {
  GRAPHQL_ERROR
  NOT_FOUND
  QUANTITY_GREATER_THAN_AVAILABLE
}

```

### Types - updated

```graphql
type OrderGrantedRefundLine {
  id: ID!
  quantity: Int!
  orderLine: OrderLine!
  
    """Reason of the granted refund."""
  reason: String
}

type OrderGrantedRefund @doc(category: "Orders") {
  id: ID!

  """Time of creation."""
  createdAt: DateTime!

  """Time of last update."""
  updatedAt: DateTime!

  """Refund amount."""
  amount: Money!

  """Reason of the refund."""
  reason: String

  """
  User who performed the action. Requires of of the following permissions: MANAGE_USERS, MANAGE_STAFF, OWNER.
  """
  user: User

  """App that performed the action."""
  app: App

  """

  !New field!

  """
  lines: [OrderGrantedRefundLine!]!
  grantRefundForShipping: Boolean!

```

### Subscription
```graphql
type TransactionRefundRequested implements Event @doc(category: "Payments") {
  """Time of the event."""
  issuedAt: DateTime

  """Saleor version that triggered the event."""
  version: String

  """The user or application that triggered the event."""
  issuingPrincipal: IssuingPrincipal

  """The application receiving the webhook."""
  recipient: App

  """Look up a transaction."""
  transaction: TransactionItem

  """Requested action data."""
  action: TransactionAction!

  """ !New field! """
  grantedRefund: OrderGrantedRefund
}
```

## 3. Database changes

```python
class OrderGrantedRefund(models.Model):
    shipping_costs_included = models.BooleanField(default=False)

class OrderGrantedRefundLine(models.Model):
    """Model used to store granted refund line for the order."""

    order_line = models.ForeignKey(
        OrderLine, related_name="granted_refund_lines", on_delete=models.CASCADE
    )
    quantity = models.PositiveIntegerField(default=0)

    granted_refund = models.ForeignKey(OrderGrantedRefund, related_name="lines", on_delete=models.CASCADE)

```

## 4. UML diagrams

```mermaid
sequenceDiagram
    User->>+Saleor: Create granted <br>refund with lines
    Saleor-->>-User: granted Refund
    User ->>+ Saleor: call transactionRequestRefundForGrantedRefund<br> with id of created<br>granted refund
    Saleor ->>+ App: Send webhook subscription<br> TransactionRefundRequested with<br>grantedRefund 
    App -->>- Saleor: 200
    Saleor -->>-User: Triggered
```

## 5. To Do list

```[tasklist]
### Tasks
- [x] Extend grantedRefund type https://github.com/saleor/saleor/pull/12858
- [x] Extend orderGrantRefund mutations https://github.com/saleor/saleor/pull/12934
- [x] Add new mutation for triggering the refund with grantedRefund https://github.com/saleor/saleor/pull/12959
- [x] Add new field to webhook subscriptions for transactions - https://github.com/saleor/saleor/pull/12967
- [x] Provide zero-downtime migration
- [ ] Update docs with a new mutation https://github.com/saleor/saleor-docs/pull/794
- [x] Bump ADDED in versions
```

## 6. To Test

- [ ] Check all points from acceptance criteria
