### ISSUE TITLE
Feature: Implement base64 blur data generation for next/image or other solutions

### ISSUE THREAD

**Issue by valiukasd** [saleor/saleor#12833]
## Problem

Since saleor core and the storefront is heavily focused on next.js and providing fast performance storefronts, I suggest adding `base64` placeholder generation for the [`next/image` component](https://nextjs.org/docs/app/api-reference/components/image#placeholder). There are tools with node.js which can generate `base64` such as [plaiceholder](https://plaiceholder.co/), but since I do not have experience with python I lack knowledge of tools which can achieve such a result, so I have a request for comments and ideas.

---

## 1. General Assumptions

The `base64` blurDataUrl would be optional and it would require extending the saleor [`Image` object](https://docs.saleor.io/docs/3.x/api-storefront/miscellaneous/objects/image), as well as generating the `base64` data itself.

### Acceptance Criteria

- [ ] As a storefront user with permissions to read products, I should be able to optionally retrieve the `base64` blurDataUrl along with the images I am serving.

### Mutations

No new mutations, just modify those which return the `Image` object

### Types

New type for `Image` object

```
type Image {
  url: String!
  alt: String
  blurDataUrl: String
}
```

## 3. Database changes

Creating  `blurDataUrl` for `Image` object

## 5. To Do list

```[tasklist]
### Tasks
- [ ] Research ways to generate blur data from images in base64
- [ ] Implement the feature in saleor core
- [ ] Have a helper function to generate blur data for existing images (in manage.py for example?)
```

## 6. To Test

Nothing to test
