### ISSUE TITLE
[RFC] Auth flow redesign

### ISSUE THREAD

**Issue by kadewu** [saleor/saleor#12849]
## Problem

As described in https://github.com/saleor/react-storefront/issues/721 we want to implement new authentication flow. We want to allow user to be able to log in even before he confirms his account.

---

## 1. General Assumptions

- User can log in before he confirms his account.
- User can manage his settings/profile after logging even if didn't confirm yet.
- User cannot see orders created before creation of the account, but can see new orders created after creation of the account
- Add new boolean flag to SiteSettings `allow_login_without_confirmation` with default value `false`
- Add new field boolean `User.is_confirmed` with default value `true`
- Add possibility to resend confirmation email

### Acceptance Criteria
- User cannot see orders created before registration.
- User with `MANAGE_SETTINGS` can query and update `SiteSettings.allow_login_without_confirmation`
- Staff user with permission `MANAGE_USERS` can update flag `is_confirmed` using mutations: `CustomerBulkUpdate`, `CustomerUpdate`.
- Changing flag `is_confirmed` to `true` using `CustomerBulkUpdate`, `CustomerUpdate` will match orders with user email
- User can re-request email confirmation in user panel.
- Changing flag `is_active` to true will not match orders with user email unless `is_confirmed` is set `true`
- User that logs for the first time via OIDC is considered as confirmed (`is_confirmed` = True)
- When `allow_login_without_confirmation` is enabled:
  - User can log in before he confirms his account. (`is_confirmed=False`)
  - User can manage his settings/profile after logging even if didn't confirm yet. (`is_confirmed=False`)
  - User that `is_confirmed=True and is_active=False` cannot login into system
  - User can see orders created **after** account creation (even when `is_confirmed=False`)
- When `allow_login_without_confirmation` is disabled (API works as in previous versions): 
  - User cannot log in before confirmation.
  - User with `is_active=False` cannot log in into system
  - User with `is_confirmed=False` cannot log in into system

### Types
```graphql
type Shop {
  ...
  "Requires one of the following permissions: MANAGE_SETTINGS."
  allowLoginWithoutConfirmation: Boolean
}

type User {
  ...
  isConfirmed: Boolean!
}
```

### Mutations
`ShopSettingsUpdate` mutation will get new input field
```graphql
input ShopSettingsInput{
  ...
  allowLoginWithoutConfirmation: Boolean
}
```

`CustomerBulkUpdate`, `CustomerUpdate` mutations will get new input field
```graphql
input CustomerInput{
  ...
  isConfirmed: Boolean
}
```

New mutation to resend confirmation email, `SendConfirmationEmail`,
```graphql
input SendConfirmationEmailInput{
  
  """Base of frontend URL that will be needed to create confirmation URL."""
  redirectUrl: String
}

"""
Requires one of the following permissions: AUTHENTICATED_USER
"""
type SendConfirmationEmail{
  errors: [SendConfrimationEmailErrors!]!
  user: User
}

type Mutation{
  ...
  sendConfirmationEmail(
    input: SendConfirmationEmailInput!
  ): SendConfirmationEmail
  
 type SendConfirmationEmailError{
   field: String
   message: String
   code: SendConfrimationEmailErrorCode!
 }
 
 enum SendConfirmationEmailErrorCode{
   INVALID
   INVALID_PERMISSION
   INVALID_URL_FORMAT
   ACCOUNT_CONFIRMED
 }
```

## 3. Database changes

`SiteSettings` model will receive new field boolean `allow_login_without_confirmation` with default value False.
`User` model will receive new field boolean `is_confirmed` with default value True.

## 4. Other

- Write migration that will check current users and set `is_confirmed`:
  - to `true` if user `is_active` or has set `last_login`
  - to `false` otherwise

- Update logic behind `CreateToken` mutation.

## 5. To Do list

```[tasklist]
### Tasks
- [ ] Confirm behaviour about transforming not confirmed user into stuff user.
- [ ] Sync work with design, dashboard and checkout team
- [ ] Update the docs
- [ ] Sync work with https://github.com/saleor/saleor/issues/12859
```
