### ISSUE TITLE
[RFC] Add a gift reward option in promotion rules

### ISSUE THREAD

**Issue by IKarbowiak** [saleor/saleor#12913]
## Problem

Allow providing the list of available gifts as a reward in the promotion rule.

Blocked by: https://github.com/saleor/saleor/issues/12889

---

## 1. General Assumptions

- Allow a `gift` option as a reward in the promotion rule
- Allow providing the list of available variants that can be a gift
- Add a `gift` field to the promotion rule

### Calculation assumptions
- When `GIFT` reward type is chosen, the `gift` is required
- Update promotions calculations - chose best promotion rule that gives the best saving for user, include gift rules in the calculations
- For savings comparison choose the available variant from the promotion rule `gifts` list with the highest `discounted_price`
- For now as a `availableDiscounts` return only promotion rule that gives the best saving
- Create an `OrderDiscount`/`CheckoutDiscount` object with the chosen promotion rule after setting the discounts with the use of `DraftOrderUpdate` or `CheckoutApplyDiscounts` mutation (we shouldn't assign promotion during order/checkout calculations, we should wait for the mutation call)
- extend `Checkout`/`Order` with `availablePromotions` field that will contain the list of the available list of promotion rules that could be attached f.e. `[[rule1_10%, rule2_gift], [rule3_gift_x2], [rule4_50%]]`
It will means that user could choose `rule1_10% and rule2_gift` OR `rule3_gift_x2` OR `rule4_50`

### Checkout/Order processing
- Allow fetching available promotion rules - currently, we will return only the rule that gives the best saving to the user
- Allow fetching available promotions on checkout and draft order
- Allow fetching chosen gifts on checkout and draft order - the gift line will be marked with `isGift` flag
- Update a checkout mutation to allow choosing promotions
- Update the draft order mutations to allow choosing promotions - currently, it will be only used for choosing a gift
- When a gift for Checkout/Order is chosen, create lines with `is_gift` flag set to True. The price for those lines should zero, and those lines shouldn't be sent to the tax plugins.
- Update the checkout and order calculations, zero down the price of a gift item
- Handle case when the gift items are already in the cart - we should create a new line for the gift and mark it as a `gift`
- The quantity for gift lines should be zero
- Do not allow to change the gift line quantity - the mutations for updating checkout and order line should be extended with proper validation
- ⚠️ The API should be able to allow choosing multiple gifts in checkout/order, but for MVP we will support providing only one gift. In next step, the reward definition should be extended by providing a number of gifts to choose.
- Allow defining limit of gifts to choose in the API - always return 1 for now

### Events
- Create events for setting and removing

### Examples
- Buy 2 cups get a gift for free
> 💡 Gift defines a list of available gifts that the user can choose from. When the list has only one item it will be added automatically
```json
{
"promotionRule": {
"checkoutAndOrderPredicate": {
 "AND": [
  {
   "discountedLineObjectPredicate": {
    "quantity": {
    	"range": {
    	  "gte": 2
    	}
    }
   }
  },
  {
   "discountedLineObjectPredicate": {
    "cataloguePredicate": {
    	"__typename": "ProductPredicate",
    	"name": {
    		"eq": "Cup"
    	}
    }
   }
  },
 ]
}
"rewardType": "GIFT",
"rewardValueType": null,
"rewardValue": 0,
"gift": ["XYZ1", "XYZ2", "XYZ3"]
}
}
```

### Acceptance Criteria

- [ ] The user can get the list of available gifts in checkout
- [ ] The user can assign the gifts in checkout
- [ ] The staff user can get the list of available gifts in draft order
- [ ] The staff user can assign the gifts in the order
- [ ] The price of chosen gifts are equal to 0

### Mutations

- Update the promotion inputs with `gifts` field
- Update the following mutations: `promotionCreate`, `PromotionRuleCreate`, `promotionRuleUpdate`:
  - Require the `gifts` field when the `GIFT` reward type is chosen
  - `rewardValueType`, `rewardValue`, `rewardPredicate` should be empty - raise an `ValidationError` otherwise
  - Validate `gifts` field - the provided ids in the `gifts` field must be the `ProductVariant` ids
- Add `CheckoutApplyDiscounts` mutation - allow assigning the promotions - raise a ValidationError when the `gifts` is provided for no gift promotion rule or gift is not in the `PromotionRule` gifts list. When the `promotions` list is empty, clear the checkout promotions
- Update `DraftOrderUpdate` mutation - allow assigning the promotions - same assumptions and validations as for `CheckoutApplyDiscounts`.
- Assigning discounts should be possible in `DraftOrderUpdate` but shouldn't be in `DraftOrderCreate`
- Update `CheckoutLinesUpdate` - don't allow to update quantity of lines marked as gift line
- Update `OrderLineUpdate` - don't allow to update quantity of lines marked as gift line

```graphql
input PromotionRuleInput @doc(category: "Discounts") {
  ...
  gifts: [ID!]
}

input PromotionRuleCreateInput @doc(category: "Discounts") {
  ...
  gifts: [ID!]
}

input PromotionRuleUpdateInput @doc(category: "Discounts") {
  ...
   gifts: [ID!]
}

input DraftOrderInput @doc(category: "Orders") {
  ...
  gifts: [ID!]
}

input DiscountInput  @doc(category: "Discounts") {
  promotionRuleID: ID!
  gifts: [ID!]
}

input DraftOrderInput @doc(category: "Orders") {
  discounts: [DiscountInput!]
}

type CheckoutApplyDiscounts @doc(category: "Checkout") {
  """An updated checkout."""
  checkout: Checkout
  checkoutErrors: [CheckoutError!]! @deprecated(reason: "This field will be removed in Saleor 4.0. Use `errors` field instead.")
  errors: [CheckoutError!]!
}

type Mutation {
  ...
  checkoutApplyDiscounts(
    id: ID
    discounts: [DiscountInput!]
  ): CheckoutApplyDiscounts @doc(category: "Checkout")
}

```

### Types

- Extend `PromotionRule` with `gifts`
- Extend `PromotionRule` with`giftsLimit` - will define the maximum number of gifts to choose from the gifts list. For now, we will always return 1, and it won't be configurable for now
- Extend `RewardTypeEnum` with GIFT 
- Extend `Checkout` with `availableDiscounts`
- Extend `Order` with `availableDiscounts`- the `availableDiscounts` should be returned only for draft orders
- Extend `OrderLine` and `CheckoutLine` with `is_gift` label
- Consider adding filter for getting lines that are `gifts`

```graphql


type PromotionRule implements Node @doc(category: "Discounts"){
  ...
  gifts: [ID!]
  giftsLimit: Int
}

enum RewardTypeEnum @doc(category: "Discounts") {
  ...
  GIFT
}

type Checkout implements Node & ObjectWithMetadata @doc(category: "Checkout") {
  ...
  availableDiscounts: [AvailableDiscounts!]
}

type Order implements Node & ObjectWithMetadata @doc(category: "Orders") {
  ...
  availableDiscounts: [AvailableDiscounts!]
}

type OrderLine implements Node & ObjectWithMetadata @doc(category: "Orders") {
  ...
  isGift: Boolean!
}

type CheckoutLine implements Node & ObjectWithMetadata @doc(category: "Checkout") {
  ...
  isGift: Boolean!
}

type: AvailableDiscounts @doc(category: "Discounts") {
  discounts: [AvailableDiscount!]
}

union AvailableDiscount = GiftDiscount | ValueDiscount

type GiftDiscount @doc(category: "Discounts") {
  promotionRuleId: ID!
  name: String
  gifts: [ID!]  # It will contain only variants that are available in given channel - for now it will return only one gift - available variant with the highest price
}

type ValueDiscount @doc(category: "Discounts") {
  promotionRuleId: ID!
  name: String
  discountAmount: PositiveDecimal!
}

```
> 💡 I created such a structure for `availableDiscounts` to be able to return a list of available promotion groups to choose like `[[rule1_10%, rule2_gift], [rule3_gift_x2], [rule4_50%]]`. Maybe we should replace this structure with a `JSON` field?
Example:
```graphql
{
  order: {
   availableDiscounts: [
    {discounts: [
      {promotionRuleID: Rule1, gifts: [ID1, ID2]},
      {promotionRuleID: Rule2, gifts: [ID3]}
    ]},
    {discounts: [
       {promotionRuleID: Rule5, discountAmount: 10}
    ]},
    {discounts: [
      {promotionRuleID: Rule4, gifts: discountAmount: 20},
      {promotionRuleID: Rule6, gifts: [ID3]},
    ]}
  }
}
```

## 3. Database changes

- Add a `gifts` field to `PromotionRule` model
- Add a `is_gift` to `CheckoutLine` model
- Add a `is_gift` to `OrderLine` model

```python
class PromotionRule:
    ...
    gifts: ManyToMany(ProductVariant)


class CheckoutLine:
    ...
    is_gift: BooleanField(default=False)

class OrderLine:
    ...
    is_gift: BooleanField(default-False)
```

## 4. To Do list

- [ ]  Extend the `rewardType` enum
- [ ]  Introduce the `gift` field
- [ ]  Update the mutations with proper validation
- [ ]  Update the order and checkout price recalculations
- [ ]  Ensure tax for flat rates and Avatax are properly calculated

## 5. To Test

- [ ] Check with price override
- [ ] Check with flat rates, avatax

## 6. Tasks
```[tasklist]
### Tasks
- [ ] https://github.com/saleor/saleor/issues/15075
- [ ] Allow choosing promotions from available options
```

## 7. Questions
- Should we return all or only one qualified amount promotion?
- Should we have separate mutations for adding and removing discounts?

**Comment by IKarbowiak** [comment]
We should allow to choose multiple gifts in checkout/order instead of one.

**Comment by IKarbowiak** [comment]
- Gift line should has qty == 1
- There should be no option to update line marked as quantity
- Consider get rid of `CheckoutAddGift` and use `CheckoutLineAdd` with a new flag `is_gift` (what about events? the events should be gift specific or should we use the line webhooks?). Potential problem with: `CheckoutLineAdd` - might become too big.
