### ISSUE TITLE
Possibility to block checkout/draft order when tax app doesn't return proper response.

### ISSUE THREAD

**Issue by korycins** [saleor/saleor#12942]
## Problem

Saleor can finalize the checkout/draft order process when Tax app doesn't provide the proper response during tax calculation.

---

## 1. General Assumptions

We will provide input for picking up the app that is responsible for processing the taxes for specific channel.
Based on the new setting and picked-up tax app we will be able to determine if we should allow to finalize the checkout process or not.
If the tax app will not be assigned to the tax configuration Saleor will work as before, that means will iterate over Apps to get tax data.

### Acceptance Criteria

- [ ] I can assign a tax app to specific taxConfiguration
- [ ] I can assign a tax app to taxConfigurationPerCountry
- [ ] Saleor doesn't allow to finalize the checkout/draft order when tax app doesn't return a correct response and taxAppId is set on taxConfiguration
- [ ] Saleor does allow to finalize the checkout/draft order when tax app is not assigned to tax configuration and settings for fail proces

#### Updated
```graphql
input TaxConfigurationUpdateInput @doc(category: "Taxes") {
  ...

  """
  The default strategy to use for tax calculation in the given channel. Taxes can be calculated either using user-defined flat rates or with a tax app. Empty value means that no method is selected and taxes are not calculated.
  """
  taxCalculationStrategy: TaxCalculationStrategy

  """
  !New fields below!
  """

  """
  The tax app id that will be used to calculate the taxes for the given channel.
  Empty value for `TAX_APP` set as `taxCalculationStrategy` means that Saleor will
  iterate over all installed tax apps.
  """
  taxAppId: String!
  
```

#### Updated
```graphql
type TaxConfiguration implements Node & ObjectWithMetadata @doc(category: "Taxes") {

  """
  The tax app id that will be used to calculate the taxes for the given channel.
  Empty value for `TAX_APP` set as `taxCalculationStrategy` means that Saleor will
  iterate over all installed tax apps.
  """
  taxAppId: String

}
```

```graphql
  type Shop {
    """
    List of tax apps that can be assigned to the channel. The list will be calculated by Saleor 
    based on the apps that are subscribed to webhooks related to tax calculations: CHECKOUT_CALCULATE_TAXES
    """
    availableTaxApps: [App!]!
  }
```

## 3. Database changes

```python
class TaxConfiguration(ModelWithMetadata):
    channel = models.OneToOneField(
        Channel, related_name="tax_configuration", on_delete=models.CASCADE
    )
    charge_taxes = models.BooleanField(default=True)
    tax_calculation_strategy = models.CharField(
        max_length=20,
        choices=TaxCalculationStrategy.CHOICES,
        blank=True,
        null=True,
        default=TaxCalculationStrategy.FLAT_RATES,
    )
    display_gross_prices = models.BooleanField(default=True)
    prices_entered_with_tax = models.BooleanField(default=True)
    
    # ----------------- Added ----------------- #
    tax_app_id = models.CharField(blank=True, null=True,max_length=256)
    calculated_taxes_required_to_place_order = models.BooleanField(default=True)
    

    class Meta:
        ordering = ("pk",)


# note: we leaved blank=True, as to be able to fallback to App.pk
class App(ModelWithMetadata):
    identifier = models.CharField(blank=True, null=False, max_length=256)
```

## 4. Changes in the code

- PluginsManager for `get_taxes_for_checkout` and `get_taxes_for_order` will receive optional input for appIdentifier.
- The basePlugin implementation for `get_taxes_for_checkout` and `get_taxes_for_order` will be extended to accept new parameters
- WebhookPlugin when receiving the appIdentifier, will trigger the request only for the app with a requested identifier. 
  - When WebhookPlugin cannot find the expected App, the retur
- TaxConfigurationUpdate will recieve additional validation for `taxAppId`. The provided taxAppId needs to be the one returned from the list of availableTaxApps

- `App.identifier` will become mandatory field:
  - all mutation related to the app should allow to set the `identifier` (local apps: create app mutation and command)
  - as a fallback the `graphqlID` will be used
  - the 0-downtime migration need to be added to propagate the `identifier` data 

- `availableTaxApps` will be calculated based on the webhooks subscribed to the expected tax webhooks.

## 5. To Do list

```[tasklist]
### Tasks
- [ ] docs should mention that `taxConfiguration.taxAppId` will become a mandatory parameter in 4.0.
- [ ] GH issue for `taxAppId` to convert it as a mandatory parameter in 4.0, with all details what should be done to correctly set this flag as a mandatory field.
- [ ] Graphql Schema  should mention that `taxAppId` will become a mandatory field for tax-app calculation strategy
- [ ] Update the docs about way how we trigger the sync webhooks for taxes
- [ ] Update ADDED_IN
- [ ] Update dashboard mutation to include one of installed taxes apps
```

## 6. To Test

- [ ]

**Comment by lkostrowski** [comment]
@kadewu please verify how we can fall back to plugin again, if we want to stop using the app

also please revsit API of strategy - can we implement something like AppTaxStrategy | PluginStrategy | FlaxRateStrategy

**Comment by lkostrowski** [comment]
@kadewu in first implementation, before we consume errors from apps, let's convert all 4xx and 5xx to TaxAppProblem

**Comment by kadewu** [comment]
Removed flag to control behaviour in scope of this task.
