### ISSUE TITLE
Better error feedback during the checkout process

### ISSUE THREAD

**Issue by korycins** [saleor/saleor#12943]
## Problem

Saleor doesn't have a way to provide non-failing feedback when something is wrong or some problems need to be handled by the customer. 
For example, if Checkout has added a product that is out of stock, any checkout mutation call will raise an exception (ref: https://github.com/saleor/saleor/issues/12938). 
Another example is a case when tax app doesn't return a proper response, and Saleor will not allow to finalize checkout (feature, described here: https://github.com/saleor/saleor/issues/12942)

---

## Status

```[tasklist]
### Tasks
- [x] Add `checkout.problems` field, include out-of-stock-errors https://github.com/saleor/saleor/pull/13077
- [x] Add settings to `channel` control legacy error flow https://github.com/saleor/saleor/pull/13044
- [x] Take into account a new settings in all checkout mutations
- [x] Update the docs to explain how the `problems` work https://github.com/saleor/saleor-docs/pull/868
- [x] Provide 0-downtime migration
- [ ] Toggle on dashboard side: https://github.com/saleor/saleor-dashboard/issues/4076
```

---

## 1. General Assumptions

We want to extend `Checkout` and `CheckoutLine` to have a new field `problems`. 
This field will store details about all problems related to checkout: like unable-to-calculate-taxes, some-products-are-out-of-stock etc
The field on `CheckoutLine` will store the details about the error related to the specific line: product-out-of-stock etc.
The `problems` field would give storefronts a better way to control the checkout process than it is currently.
Saleor will allow you to modify the checkout even if something is wrong (case: updating shipping address and some of the product is out of stock - described here https://github.com/saleor/saleor/issues/12938).
The checkoutComplete will still raise an exception in case of any problem, but with `problems` field storefront will know earlier any potential problems. 

The error that we could port is the one explained in https://github.com/saleor/saleor/issues/12938. 

Note: 
The scope of this RFC is building a better interface for managing the errors, not migrating ALL potential `problems` to new interface.

### Acceptance Criteria

- [x] Checkout has field `problems`
- [x] CheckoutLine has field `problems`
- [x] `problems` fields are accessible from graphqlAPI and don't require any permission
- [x] `problems` contains the info when product is out of stock
- [x] if anything listed in `problems`, checkoutComplete & orderCreateFromCheckout should raise an exception

#### Channel

```graphql
input checkoutSettingsInput @doc(category: "Checkout") {
    """
    Default `true`. Determines if the checkout mutations should use legacy 
    error flow. In legacy flow, all mutations can raise an exception 
    unrelated to the requested action - (e.g. out-of-stock exception when updating 
    checkoutShippingAddress.)
    If `false`, the errors will be aggregated in `checkout.problems` field. 
    Some of the `problems` can block the finalizing checkout process.
    The legacy flow will be removed in Saleor 4.0. 
    The flow with `checkout.problems` will be the default one.
    """
    useLegacyErrorFlow: Boolean
}
input ChannelCreateInput @doc(category: "Channels") {
    checkoutSettings: checkoutSettingsInput
}

input ChannelUpdateInput @doc(category: "Channels") {
    checkoutSettings: checkoutSettingsInput
}
```

##### CheckoutLine
```graphql
type CheckoutLineProblemInsufficientStock{
  availableQuantity: Int!
  line: CheckoutLine!
  variant: ProductVariant!
}

type CheckoutLineProblemProductNotPublished{
  line: CheckoutLine!
}

union CheckoutLineProblem = CheckoutLineProblemInsufficientStock | CheckoutLineProblemProductNotPublished

"""Represents an item in the checkout."""
type CheckoutLine implements Node & ObjectWithMetadata @doc(category: "Checkout") {
  id: ID!
  problems: [CheckoutLineProblem!]!
}
```

#### Checkout
```graphql
type CheckoutProblemBillingAddressInvalid {
  address: AddressValidationData!
}

type CheckoutProblemShippingAddressInvalid {
  address: AddressValidationData!
}

type CheckoutProblemShippingMethodInvalid {
  debugMessage: String
}

type CheckoutProblemUnableToCalculateTaxes {
  debugMessage: String
}

union CheckoutProblem = CheckoutLineProblemInsufficientStock | CheckoutLineProblemProductNotPublished | CheckoutProblemBillingAddressNotSet | CheckoutProblemShippingAddressNotSet | CheckoutProblemShippingMethodNotSet

type Checkout implements Node & ObjectWithMetadata @doc(category: "Checkout") {
  id: ID!
  problems: [CheckoutProblem!]!
}
```

##### Channel
```graphql
type CheckoutSettings {
    """
    Default `true`. Determines if the checkout mutations should use legacy 
    error flow. In legacy flow, all mutations can raise an exception 
    unrelated to the requested action - (e.g. out-of-stock exception when updating 
    checkoutShippingAddress.)
    If `false`, the errors will be aggregated in `checkout.problems` field. 
    Some of the `problems` can block the finalizing checkout process.
    The legacy flow will be removed in Saleor 4.0. 
    The flow with `checkout.problems` will be the default one.
    """
    useLegacyErrorFlow: Boolean!
}

"""Represents channel."""
type Channel implements Node @doc(category: "Channels") {
    checkoutSettings: CheckoutSettings!
}
```

## 3. Database changes
```python
class Channel(models.Model):
    use_legacy_error_flow_for_checkout = models.BooleanField(default=True)
```
We could consider the denormalization of the `problems` in case of huge amount
of actions that need to be done to calculate all problems on the resolver lvl.

## 4. Changes in code logic

When channel.use_legacy_error_flow_for_checkout is False:

Checkout mutations will not raise an exceptions that are not related to the given action. Instead, the new object will be added to `problems`.
For example mutation checkoutShippingAddressUpdate, will no longer trigger the OUT_OF_STOCK exception. Instead, OUT_OF_STOCK error will be listed in the `problems` section, and the finalization of the checkout will not be available.

When channel.use_legacy_error_flow_for_checkout is True:

Checkout mutations will work as previously.

## 5. To Test

- [ ]
- [ ]

**Comment by korycins** [comment]
Draft of the `Problems` that can be added in future:
```python
class CheckoutProblemBillingAddressInvalid:
    ...

class CheckoutProblemShippingAddressInvalid:
    ...

class CheckoutProblemShippingMethodInvalid:
    ...

class CheckoutLineProbleQuantityGreaterThanLimit:
    ...

class CheckoutProblemVoucherNotApplicable:
    ...

class CheckoutProblemGiftCardNotApplicable:
    ...

class CheckoutProblemNoLines:
    ...

class CheckoutProblemEmailNotSet:
    ...
```

**Comment by lkostrowski** [comment]
@kadewu @korycins please sync on the API and ensure both taxes and payments endpoints will share the same interface for setting errors

Also consider errors on orders. If its not scope of this issue, we can describe it fo next work

**Comment by lkostrowski** [comment]
@korycins please create a seprate task for these extra problems + close this one

**Comment by korycins** [comment]
@lkostrowski  I've extracted the potential problems into separate task: https://github.com/saleor/saleor/issues/14588

**Comment by korycins** [comment]
Clossing the issue, as everything is covered or handled by separate tasks.
