### ISSUE TITLE
[RFC] Payment Requests

### ISSUE THREAD

**Issue by witoszekdev** [saleor/saleor#12976]
# Problem

There is no way in Saleor to request a payment from user and generate pay-by-links from Payment Provider Apps from Customer Support perspective.

## Goals

- Add API for requesting payment from users: `PaymentRequest`
  - Add mutation for staff members to request a payment for the order / draft order from customer
  - Add async webhook for receiving notifications about payment requests
  - Users can fetch a list of payment requests in storefront
- Add API for generating pay-by-links from Payment Provider Apps
  - Add mutation for requesting a pay-by-link to a created `PaymentRequest`
  - Add sync webhook for generating pay-by-link that will be used by Payment Provider App
  - This API should be optional: a store might not use pay-by-links from Payment Provider and instead use a custom implementation

## Non Goals

- Saleor shouldn't send any notifications to users directly, it should be handled by an external app by subscribing to available webhooks
- Programmatic charges: they are handled in a separate RFC

# API Changes

## Requesting payment from customer

![Request customer payment](https://github.com/saleor/saleor/assets/4144459/3cf2d92d-7f01-4332-8072-dabedbed3d9c)

This flow can be used if the customer doesn’t have a Payment Method saved in any of the payment providers and payment is required to proceed with the order.

Example: you create an order for a preorder and customer pays a deposit, before sending the order you request the customer to pay the remaining amount.

Example: customer requested to add items to an unfulfilled order, you add them to the order and request the customer to pay the remaining amount.

→ [See a flowchart for this flow](#requesting-customer-to-pay-for-an-outstanding-order)

### `orderRequestPayment` mutation

```graphql
eunm OrderRequestPaymentErrorCode {
  GRAPHQL_ERROR
  INVALID
  ORDER_NOT_FOUND
  INVALID_EXPIRE_DATE
}

type OrderRequestPaymentError {
  field: String
  message: String
  code: OrderRequestPaymentErrorCode!
}

type OrderPaymentRequest {
  order: Order
  errors: [OrderRequestPaymentError]
}

type PaymentRequest {
  """Date at which the payment request was created on"""
  createdAt: DateTime!
  """
  Staff member that requested the payment

  Required permission: HANDLE_ORDERS
  """
  initiatedBy: User!
  """Expiration date, after which the request will no longer be available"""
  expiresAt: DateTime
  """Additional message for the customer"""
  message: String
  """Amount that needs to be paid by customer"""
	amount: Money!
  """Order for which the PaymentRequest was issued for"""
  order: Order!
}

type Mutation {
  """
  Requests payment for the order from user. It will trigger ORDER_PAYMENT_REQUESTED webhook

	Required permission: HANDLE_ORDERS

  Added in Saleor 3.xx
  """
  orderRequestPayment(
    """Order that needs to be paid"""
    orderId: ID!,
    """Specify custom amount to be paid by customer. By default it's order.totalBalance"""
		amount: PositiveDecimal,
    """
		Expiration date, after which the request will be no longer valid

		By default it uses settings from order's channel specified in `OrderSettings.paymentRequestDefaultExpirationDate`
		"""
    expiresAt: DateTime
    """Additional message sent to the customer"""
    message: String
  ): OrderPaymentRequest
}

type Order {
  # ...
  paymentRequests: [PaymentRequest!]
}

type User {
  # ...
  paymentRequests: [PaymentRequest!]
}
```

### Setting default expiration date: `channelUpdate` mutation

Update `OrderSettingsInput` type used in `channelUpdate` mutation to set default expiration date of payment requests

```graphql
scalar Infinity

type OrderSettingsInput {
  # ...
  """
  Used by `orderRequestPayment` mutation when requesting a payment for the order by customer.

  When Infinity is used the payments requests don't expire

	Added in Saleor 3.xx
  """
  paymentRequestDefaultExpirationDate: TimePeriod | Infinity
}
```

### `ORDER_PAYMENT_REQUESTED` [Async webhook]

After a staff member requests a payment by using `orderRequestPayment` mutation, a call to this webhook will be sent.

```graphql
type OrderPaymentRequested implements Event {
  """
  Time of the event.
  """
  issuedAt: DateTime

  """
  Saleor version that triggered the event.
  """
  version: String

  """
  The user or app that triggered the event.
  """
  issuingPrincipal: IssuingPrincipal

  """
  The application receiving the webhook.
  """
  recipient: App

  """
  Order that needs to be paid
  """
  sourceObject: Order!

  """
  Amount that customer needs to pay.
  """
  amount: Money

  """
  Expiration date, after which the request will be no longer valid
  """
  expiresAt: DateTime

  """
  Additional message sent to the customer about the payment request
  """
  message: String
}
```

An app that handles the messaging to customers (email, push, etc.) should subscribe to this webhook and sent a notification with call to action to the customer. It should provide an instruction on how to pay for the order.

### Paying for the order

Use the [Payments App flow described in Saleor Docs](https://docs.saleor.io/docs/3.x/developer/payments#processing-a-payment-with-payment-app):

In [`paymentGatewayInitialize`](https://docs.saleor.io/docs/3.x/api-reference/payments/mutations/payment-gateway-initialize) provide the ID of the `Order` that needs payment.

# Workflow

## Requesting customer to pay for an outstanding order

```mermaid
sequenceDiagram
    actor CS as Customer Support
    actor Customer

    CS->>Saleor: orderRequestPayment mutation
    Saleor->>Email App: ORDER_PAYMENT_REQUESTED webhook
    Email App->>Customer: Sends email
    Customer->Customer: Reads email, goes to the storefront page
    Customer->>Storefront: Visits checkout page

    rect rgba(194, 219, 255, 0.2)
        note over Storefront: Uses "Processing a payment with Payment App" flow
        Storefront->>Saleor: Channel.availablePaymentGateways query
        Saleor->>Storefront: Returns list of payment gateways
        Storefront->>Saleor: paymentGatewayInitialize mutation, with amount = 0
        par Initlizing payment gateways
        Saleor->>Adyen App: PAYMENT_GATEWAY_INITIALIZE_SESSION webhook
        Adyen App->>Adyen API: Create session
        Adyen API->>Adyen App:
        Adyen App->>Saleor: Return session data for dropin
        end
        Saleor->>Storefront: Returns session data from payment apps

        Customer->>Storefront: Enters credit card data (through iframe)
        Storefront->>Saleor: transactionInitialize mutation
        Saleor->>Adyen App: TRANSACTION_INITIALIZE_SESSION webhook
        Adyen App->>Adyen API: Charge customer
        Adyen API->>Adyen App: Return pspReference
        Adyen App->>Saleor: Respond to TRANSACTION_INITIALIZE_SESSION webhook
        Saleor->>Storefront: Return created transaction
        note over Adyen API: processes charge asynchronously
        Adyen API->>Adyen App: Charge result
        Adyen App->>Saleor: transactionEventReport mutation
    end
    Customer->>Storefront: Chooses default payment method to pay for future orders
    Storefront->>Saleor: paymentMethodSetDefault mutation
```

# TO-DO list

- [ ] Order payment request API
  - [ ] Add `orderRequestPayment` mutation and types
  - [ ] Update `User` to have `paymentRequests` list
  - [ ] Update `channelUpdate` to have `OrderSettingsInput.paymentRequestDefaultExpirationDate`
  - [ ] Add `ORDER_PAYMENT_REQUESTED` webhook
