### ISSUE TITLE
enable multiple categories on a product

### ISSUE THREAD

**Issue by nathanschwarz** [saleor/saleor#13046]
## Problem

I'm currently creating a store for an Art gallery.
Each artwork must be filterable by the technique used, eg:
- prints : etching, litograph, posters, photos, etc.
- sculptures
- canvas
...

Each artwork must also be filterable by topics and subtopics, eg : 
- animals : birds, cats, dogs, ....
- landscapes: city, countryside, ...
- vehicles : planes, cars, buses, ...
...

it can also be an union of these values, eg : ['litograph', 'countryside', 'cows', 'pigs', 'tractors'].
I've been using attributes and attributes values to hold this data (saving the parent ID in the `attributeValue.richText` field).
This is quite cumbersome to do, since I need to pass all attributes values in the tree to the product, eg: 
["prints", "litograph", "animals", "pigs", "cows", "vehicules", "tractors" ]

This feature is already baked in Categories (tree filtering), but a product only accept one.
---

## 1. General Assumptions

It makes more sense to attach multiple categories to a product.

### Types

```graphql
input ProductBulkCreateInput {
  attributes: [AttributeValueInput!]
  category: [ID!]
  chargeTaxes: Boolean
  collections: [ID!]
  description: JSONString
  name: String
  slug: String
  taxClass: ID
  taxCode: String
  seo: SeoInput
  weight: WeightScalar
  rating: Float
  metadata: [MetadataInput!]
  privateMetadata: [MetadataInput!]
  externalReference: String
  productType: ID!
  media: [MediaInput!]
  channelListings: [ProductChannelListingCreateInput!]
  variants: [ProductVariantBulkCreateInput!]
}
input ProductInput {
  attributes: [AttributeValueInput!]
  categories: [ID!]
  chargeTaxes: Boolean
  collections: [ID!]
  description: JSONString
  name: String
  slug: String
  taxClass: ID
  taxCode: String
  seo: SeoInput
  weight: WeightScalar
  rating: Float
  metadata: [MetadataInput!]
  privateMetadata: [MetadataInput!]
  externalReference: String
}
type Product implements Node, ObjectWithMetadata {
  id: ID!
  privateMetadata: [MetadataItem!]!
  privateMetafield(key: String!): String
  privateMetafields(keys: [String!]): Metadata
  metadata: [MetadataItem!]!
  metafield(key: String!): String
  metafields(keys: [String!]): Metadata
  seoTitle: String
  seoDescription: String
  name: String!
  description: JSONString
  productType: ProductType!
  slug: String!
  categories: [Category!]
  created: DateTime!
  updatedAt: DateTime!
  chargeTaxes: Boolean!
  weight: Weight
  defaultVariant: ProductVariant
  rating: Float
  channel: String
  descriptionJson: JSONString
  thumbnail(size: Int, format: ThumbnailFormatEnum = ORIGINAL): Image
  pricing(address: AddressInput): ProductPricingInfo
  isAvailable(address: AddressInput): Boolean
  taxType: TaxType
  attribute(slug: String!): SelectedAttribute
  attributes: [SelectedAttribute!]!
  channelListings: [ProductChannelListing!]
  mediaById(id: ID): ProductMedia
  imageById(id: ID): ProductImage
  variant(id: ID, sku: String): ProductVariant
  variants: [ProductVariant!]
  media(sortBy: MediaSortingInput): [ProductMedia!]
  images: [ProductImage!]
  collections: [Collection!]
  translation(languageCode: LanguageCodeEnum!): ProductTranslation
  availableForPurchase: Date
  availableForPurchaseAt: DateTime
  isAvailableForPurchase: Boolean
  taxClass: TaxClass
  externalReference: String
}
```

## 3. Database changes

add a table `product_categoryproduct` similar to `product_collectionproduct` and replace `collection_id` field with `category_id` field.

## 5. To Do list

```[tasklist]
### Tasks
- [ ] create the db migration
- [ ] update the corresponding graphql types, queries and mutations (if any).
- [ ] update all DB queries using the current `product_product.category` field.
- [ ] update unit tests
```

**Comment by timuric** [comment]
@nathanschwarz categories are designed to be 1 to 1 relationship, and collections one to many. This is by design, as some apps rely on 1 to 1 relationships for taxes, product feeds etc.
