### ISSUE TITLE
[RFC] Add a flag to channel to allow placing unpaid orders from checkoutComplete

### ISSUE THREAD

**Issue by kadewu** [saleor/saleor#13073]
## Problem

https://github.com/saleor/saleor/issues/13016
We want to have possibility to complete checkout with order before successful payment.

## 1. General Assumptions

- New `Channel` flag `allow_unpaid_orders`.
- When flag `allow_unpaid_orders` on channel is `False` flow will not be affected.
- `allow_unpaid_orders` will result in creating order in TRANSACTION_FLOW
- Changes affects only `checkoutComplete` mutation

### Acceptance Criteria
- [ ] Add new boolean flag to `Channel`: `allow_unpaid_orders`
- [ ] User with `MANAGE_CHANNELS` or `MANAGE_ORDERS`  can update flag `allow_unpaid_orders`.
- [ ] When `allow_unpaid_orders` is disabled, completeCheckout requires successful payment to process.
- [ ] When `allow_unpaid_orders` is enabled, user can create order from checkout even if the payment isn't successful.

### Types

```graphql
input: OrderSettingsInput {
  ...
  """Allows to create order before payment"""
  allowUnpaidOrders: Boolean!

```

type OrderSettings{
  ...
  allowUnpaidOrders: Boolean!
}

### Other

Update logic regardless processing the payment and creating the order from checkout. 

## 3. Database changes

New boolean field in `Channel` model: allow_unpaid_orders with default value `False`

## 5. To Do list

```[tasklist]
### Tasks
- [ ] Sync with checkout/dashboard teams
- [ ] Update docs - new subchapter with new flow for finalizing checkout
- [ ] Document order expiration settigs
```

**Comment by korycins** [comment]
I would suggest different name for `checkout_complete_create_order_first`. It should be something like: `allow-to-create-order-without-payment` or something with `checkout-complete` name but with something that suggests that we will allow you to create order without a processed payment.

---
Also worth mentioning, the flag will have an impact only on the transactionAPI. It will not change the behaviour of the old PaymentAPI

---
We should also update the docs  for finalizing the checkout process, where we place the subchapter that will describe the flow where we create the order without payment. The chapter should also mention, that at the beginning we lock the prices, stocks, etc for the order, then based on the settings for expireOrder, we mark them as expired and release the stocks (if not have any payment), and delete it after X days.

**Comment by korycins** [comment]
I believe that the new flag should be able to control by staff user with MANAGE_ORDERS

**Comment by maarcingebala** [comment]
@Yahyaali1 Does it happen in Saleor Cloud or on your local instance of Saleor?

**Comment by korycins** [comment]
@Yahyaali1  This change is included in 3.15. It looks like you have a dashboard in 3.15 and a core in 3.14
