### ISSUE TITLE
Add Deplot to Railway

### ISSUE THREAD

**Issue by ImBIOS** [saleor/saleor#13081]
## Problem

I found Deploy to Heroku button in the README file, but... I want to use the Railway instead of Heroku. I'm trying to make it myself in here: https://railway.app/button, but I have no idea what infrastructure required to start the demo in the Railway platform

---

### Acceptance Criteria

- [ ] A button visible to deploy Saleor demo in Railway
- [ ] Demo instance is started and running properly after deployed to Railway

### Mutations

_undefined_

### Types

_undefined_

## 3. Database changes

_undefined_

## 4. UML diagrams

_undefined_

## 5. To Do list

```[tasklist]
### Tasks
- [ ] Create a "Deploy to Railway" button using https://railway.app/button
- [ ] Add a "Deploy to Railway" button into README
```

## 6. To Test

_undefined_

**Comment by patrys** [comment]
We no longer have "Deploy to Heroku," and the only deployment methods recommended and supported by our team are ones based on Docker or Kubernetes. Please consider contributing to the deployment section of Saleor documentation instead.
