### ISSUE TITLE
Add `checkoutAndOrderPredicate` to Promotion Rules for checkout/order total and subtotal

### ISSUE THREAD

**Issue by IKarbowiak** [saleor/saleor#13330]
Part of https://github.com/saleor/saleor/issues/12889

Implement all required logic from https://github.com/saleor/saleor/issues/12889 to allow defining only `totalPrice ` and `subtotalPrice` in `discountedObjectPredicate ` in `CheckoutAndOrderPredicateInput`

## 1. General Assumptions
- Allow define `rewardType` on `PromotionRule`
- Allow defining `rewardType` only for rules with `checkoutAndOrderPredicate`. In case od catalogue discounts the reward type is implied by `rewardValuType` (fixed/percentage)
- Allow defining `checkoutAndOrderPredicate` in promotion and promotion rules mutations
- Allow defining predicates based on `totalPrice` and `subtotalPrice` of checkout and order
- Apply the discounts in checkout and order calculations
- Ensure the tax are correctly calculated
- Add a validation in `PromotionRule` mutations to not allow providing both `checkoutAndOrderPredicate` and `cataloguePredicates`. The promotion rule discount should be applied on catalogue level or on order/checkout level. If we would allow to mix those it will be not clear where we should apply the discount - on catalogue or on order level. So to make it clear the rule should provide catalogue discount (that will reduce the variant price) or checkout/order discount that will be applied during order creation.
- One promotion can only have checkout rules OR catalogue rules - add a validation in `Promotion` and `PromotionRule` mutations to not allow mixing those types of rules
- During calculation, we should choose the `promotion` that gives the best discount for the user.

**For calculations**
- Implement a solution to apply the promotion that gives the greatest saving from all promotions that applied on the order.
- When the manual discount is given ignore discounts from promotions - include such info in API field description and docs
- For total and subtotal price conditions we should take into consideration price that is default for user (which depend on the configuration flag `prices_entered_with_tax`)
- Vouchers and promotion discounts are not mixes, when the voucher is given, do not calculate the promotion discounts

### Examples:
20% discount on subtotal when you spend at least $100
```json
{
    "promotionRule": {
        "checkoutAndOrderPredicate": {
            "discountedObjectPredicate": {
                "subtotalPrice": {
                    "range": {
                        "gte": 100
                     }
                  },
              }
        },
        "rewardType": "SUBTOTAL_DISCOUNT"
        "rewardValueType": "PERCENTAGE",
        "rewardValue": 20
    }
}
```

### Mutations
- Allow defining `checkoutAndOrderPredicate` and `rewardType` during promotion creation: add `checkoutAndOrderPredicate` and `rewardType` to `PromotionCreateInput`
- Allow defining `checkoutAndOrderPredicate` and `rewardType`  in `PromotionRuleCreate` and `PromotionRuleUpdate` mutations: add `checkoutAndOrderPredicate` and `rewardType` to `PromotionRuleCreateInput` and `PromotionRuleUpdateInput`

- Require providing `rewardType` when `checkoutAndOrderPredicate` is provided
- Raise an error when `rewardType` is provided for `cataloguePredicate`
- Allow providing only `checkoutAndOrderPredicate` or `catloguePredicate`. Raise an error when both value are provided.
- Do not allow mixing `catalogue` with `checkout/order` rules within promotions. Raise an error when `catalogue` rule is defined in `Promotion` with `checkout/order` rules. The validation should be added in `PromotionCreate`, `PromotionRuleCreate`, `PromotionRuleUpdate` mutations
- Raise an error when the price based predicate (`subtotalPrice`, `totalPrice`) is provided for rule with multiple channels with different currencies

```graphql
input PromotionRuleInput @doc(category: "Discounts") {
  ...
  checkoutAndOrderPredicate: CheckoutAndOrderPredicateInput
  rewardType: RewardTypeEnum
}


input PromotionRuleCreateInput @doc(category: "Discounts") {
  ...
  checkoutAndOrderPredicate: CheckoutAndOrderPredicateInput
  rewardType: RewardTypeEnum
}

input PromotionRuleUpdateInput @doc(category: "Discounts") {
  ...
  checkoutAndOrderPredicate: CheckoutAndOrderPredicateInput
  rewardType: RewardTypeEnum
}

input CheckoutAndOrderPredicateInput @doc(category: "Discounts") {
  discountedObjectPredicate: DiscountedObjectPredicateInput
  AND: [CheckoutAndOrderPredicateInput!]
  OR: [CheckoutAndOrderPredicateInput!]
}


input DiscountedObjectPredicateInput @doc(category: "Discounts"){
  subtotalPrice: DecimalFilterInput
  totalPrice: DecimalFilterInput
  AND: [DiscountedObjectPredicateInput!]
  OR: [DiscountedObjectPredicateInput!]
}
```

### Types
- Add `RewardTypeEnum` with `SUBTOTAL_DISCOUNT`
- Add `CheckoutAndOrderPredicate`
- Extend `PromotionRule` with `rewardType` and `checkoutAndOrderPredicate` fields

```graphql
type PromotionRule implements Node @doc(category: "Discounts"){
  ...
  checkoutAndOrderPredicate: JSON
  rewardType: RewardTypeEnum
}

enum RewardTypeEnum @doc(category: "Discounts") {
  SUBTOTAL_DISCOUNT
}

```

## 3. Database changes
- Extend `PromotionRule` with `reward_type` and `checkout_and_order_perdicate`
```python
class PromotionRule:
    ...
    checkout_and_order_predicate: JSONField
    reward_type: CharField
```

- Add `CheckoutDiscount` (similar to `OrderDiscount`) that will keep discount applied on the whole `Checkout` instead of each line

## 4. Calculations
We should apply the discount that gives the best savings for the user
```mermaid
---
title: The order in which discounts apply
---
graph TD
    A(Base undiscounted price) --> B[Apply catalogue discounts]
    B --> Z{Manual discount or voucher code added?}
    Z --> |No| K[Apply `checkoutAndOrder` discount]
    K --> E
    Z --> |Yes| C[Apply lines vouchers - `ONCE_PER_ORDER`, `SPECIFIC_PRODUCT`]
    C --> D[Apply `ENTIRE_ORDER` voucher]
    D --> E[Apply taxes]
```

```mermaid
---
title: Applying `checkoutAndOrder` discount
---
graph TD
    A(Base discounted price) --> B[Collect all `checkoutAndOrder` promotion rules that apply]
    B --> C[Find the rule that gives the best saving for user]
    C --> D[Choose the promotion rule with the best saving]
    D --> E[Apply chosen promotion rule on discounted price]
    E --> F[Create a corresponding `OrderDiscount` or `OrderLineDiscount` object]
```

- Create `where` filter inputs for `DiscountedObjects` for `Checkout` and `Order` that will include all fields from `DiscountedObjectPredicate`
- Create `where` filter inputs for `DiscountedObjects` for `CheckoutLine` and `OrderLine` that will include all fields from `DiscountedObjectLinePredicate`
- Add a helper function similar to `get_variants_for_predicate` that will return checkouts or orders that fulfil predicate conditions. The function should gets the checkouts/orders queryset, to operate only on interesting qs. Depending if the qs is `Checkout` or `Order` type, the function should use order or checkout filter inputs for calculations.
- Add a helper function for fetching applicable promotion rules for given `Checkout` or `Order` (similar to `fetch_active_promotion_rules`). The method should take into consideration only promotions that has defined `catalogueAndOrderPredicate`. 

### Checkout calculations
- Update checkout calculations - `_fetch_checkout_prices_if_expired` should check if any rules applies on this checkout. If multiple rules apply, we should choose the promotion rule that gives the best discount for the user. The discount should be saved in `CheckoutDiscount` or `CheckoutLineDiscount` (if the reward type is `SPECIFIC_PRODUCT_DISCOUNT`) objects
- Add tests for mutations like `CheckoutCreate`, `CheckoutLinesAdd`, `CheckoutLineDelete`, check the conditions if prices are properly recalculated if the checkout/order does not fit the rules conditions anymore 

### Order calculations
- Update order calculations - `_fetch_order_prices_if_expired` should check if any rules applies on this order. If multiple rules applies, we should calculate the best discount for user (rules discounts are combined within single promotion). The discount should be saved in `OrderDiscount` or `OrderLineDiscount` (if the reward type is `SPECIFIC_PRODUCT_DISCOUNT`) objects.
- Add tests for mutations like `DraftOrderCreate`, `OrderLinesAdd`, `OrderLineDelete`, check the conditions if prices are properly recalculated if the checkout/order does not fit the rules conditions anymore 

- The discounts should be included in the tax calculations. It should be handled in the same way as currently. So when the discount applies to subtotal or entire object, we're sending it as a separate discount object to TaxApp. The tax app responsibility was to propagate the discount on the lines. 

## 5. Questions/Problems
- Optimization issue to consider. Going though all promotion rules with `checkoutAndOrderPredicate` defined might take too long time. We should consider the solution to ensure it will not take too long when a number of promotion rules grows.
We need to keep in mind that conditions might be complex like the examples below:

```json
{
    "promotionRule": {
        "checkoutAndOrderPredicate": {
            "AND": [
                {
                    "discountedObjectPredicate": {
                        "OR": [
                            {"userPredicate": {"isStaff": true}},
                            {"subtotalPrice": {"range": {"gte": 100}}}
                        ]
                    }
                },
                {
                    "discountedLineObjectPredicate": {
                        "quantity": {
                            "range": {
                                "gte": 3
                            }
                        },
                        "cataloguePredicate": {
                            "categoryPredicate": {
                                "name": {
                                "eq": "Shirt"
                                }
                            }
                        }
                    }
                }
            ]
        },
        "rewardType": "SUBTOTAL_DISCOUNT"
        "rewardValueType": "PERCENTAGE",
        "rewardValue": 20
    }
}
```

Proposition:
1. We can implement the basic solution with filter and test it on data with big amount of products, variants, promotions - check if it's problematic.
2. Maybe we can consider the limit of number of rules that defines `checkoutAndOrderPredicate`
3. If we consider it from the start as a problematic, maybe we should create some helper mapping for each condition that we allows to filter by. E.g. for subtotal and total we can define the ranges and include the promotion rules ids that should be checked for order/checkout that match the specific range. The range creation might happened in the background.
Question here, how the range size should be defined, also we would need such mapping for each currency separately.
We could also have similar mapping for product based conditions. 

## 6. TODO list

```[tasklist]
### Tasks
- [ ] https://github.com/saleor/saleor/issues/14585
- [ ] https://github.com/saleor/saleor/issues/14586
- [ ] https://github.com/saleor/saleor/issues/14587
```

**Comment by aniav** [comment]
1. Would be good to add why we don't want to allow providing both `checkoutAndOrderPredicate` and `cataloguePredicates`. I have context about the whole feature and this is not clear to me.
2. I'd say we should go with a limit to start with and then when we're comfortable with performance allow increasing that.

Aside from that 👌

**Comment by korycins** [comment]
> 1. Would be good to add why we don't want to allow providing both `checkoutAndOrderPredicate` and `cataloguePredicates`. I have context about the whole feature and this is not clear to me.

---

>  The promotion rule discount should be applied on catalogue level or on order/checkout level. If we would allow to mix those it will be not clear where we should apply the discount - on catalogue or on order level. So to make it clear the rule should provide catalogue discount (that will reduce the variant price) or checkout/order discount that will be applied during order creation.

What about a case, when I have promotion rule for catalogue and the second one with `checkoutAndOrderPredicate`? Will we apply both? 

---

Are we 100% sure that having single object for `checkout` and `order`:  `checkoutAndOrderPredicate` is correct way here? 
Separate objects sound more future-proof for me, as they allow us to extend predicates for single object.  (for example, you could have a predicate for order, where discount shouldn't be applied when staff user applied discount for the order).
