### ISSUE TITLE
[RFC] Vouchers unlocking promotions

### ISSUE THREAD

**Issue by IKarbowiak** [saleor/saleor#13582]
## Problem

We want to introduce the option to apply vouchers codes only when specific conditions are met.

As we're introducing the promotions with rules, it seems like both discounts could me merged together. The idea is to rename `Promotion` to `Discount`.
Under the new structure, discounts will have additional optional voucher codes. These codes will be available for discounts with rules for `checkoutAndOrderPredicate`s or without any rules. When there are no voucher codes, it will be treated as a standard promotion. If the discount has voucher codes, but no promotions rules, it will be treated as normal voucher codes, without any restrictions.
---

## 1. General Assumptions

- Rename `Promotion` to `Discount` (and all related mutations and queries)
- Rename `PromotionRule` to `DiscountRule` (and all related mutations and queries)
- The `Discount` without voucher codes will be treated as `Promotion`
- The voucher code could be added only when discount has only  rules with `checkoutAndOrderPredicate` or has no rules
- The discount with voucher codes and without any rules will be treated as standard voucher code
- The rules conditions will be checked when the voucher code will be added to checkout

### Acceptance Criteria

- [ ] Adding a voucher to discount with rules that specifies `checkoutAndOrderPredicate` will raise an error
- [ ] The voucher is applied in checkout only when the conditions from rules are fulfilled
- [ ] The voucher from discount with voucher codes without any rules should be always applied on checkout

### Mutations
Rename promotion mutations:
```graphql
  discountCreate(
    """Fields requires to create a discount."""
    input: DiscountCreateInput!
  ): DiscountCreate @doc(category: "Discounts")

  discountUpdate(
    """ID of the discount to update."""
    id: ID!

    """Fields required to update a discount."""
    input: DiscountUpdateInput!
  ): DiscountUpdate @doc(category: "Discounts")

  discountDelete(
    """The ID of the discount to remove."""
    id: ID!
  ): DiscountDelete @doc(category: "Discounts")


```

### Types

```graphql

```

## 4. To Do list

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

## 5. To Test

- [ ]
- [ ]

**Comment by IKarbowiak** [comment]
Good question here. I think yes, the `code` will return first code, same `used` will returned `used` from the first `code`. What about type, we will take this from the first `rule`. I will update the description with those assumptions. Thanks @korycins
