### ISSUE TITLE
`customerIpAddress` for transactionAPI

### ISSUE THREAD

**Issue by korycins** [saleor/saleor#13605]
## Problem
Some payment providers would require to have provided ip of the customer to successfully process the payment. Currently transactionItem doesn't store this info. 

---

## 1. General Assumptions

We will extend the `transactionItem` model by adding `customer_ip` field. The API will also receive an optional protected field for setting up the value. 

### Acceptance Criteria
- [ ] Transaction API has a field for setting up the `customerIPAddress`
- [ ] The input field `customerIPAddress` is an optional field
- [ ] `customerIPAddress` in transactionIntialize mutation requires `HANDLE_PAYMENTS` permission. Same approach as we have for `action` field.
- [ ] Saleor set up the ip address if not provided in the input.

#### transactionInitialize
```graphql
  transactionInitialize(

    """
    The customer IP address. If not provided Saleor will try to determine the customer's IP address on its own. 
    The field can be used only by app that has `HANDLE_PAYMENTS` permission.
    """
    customerIpAddress: String

    """The ID of the checkout or order."""
    id: ID!

    """Payment gateway used to initialize the transaction."""
    paymentGateway: PaymentGatewayToInitialize!
  ): TransactionInitialize @doc(category: "Payments")
```

#### TransactionCreate
``` graphql
input TransactionCreateInput @doc(category: "Payments") {
  ...
  """
  The customer IP address. If not provided Saleor will try to determine the customer's IP address on its own.
  """
  customerIpAddress: String
}
```

#### TransactionUpdate
``` graphql
input TransactionUpdateInput @doc(category: "Payments") {
  ...
  """
  The customer IP address. If not provided Saleor will try to determine the customer's IP address on its own.
  """
  customerIpAddress: String
}
```

### Types

```graphql
type TransactionItem {
  ...
  """The customer IP address."""
  customerIpAddress: String
}
```

## 3. Database changes

```python
class TransactionItem(ModelWithMetadata):
  customer_ip_address = models.GenericIPAddressField(blank=True, null=True)
```

## 4 To Do list

```[tasklist]
### Tasks
- [ ] Add field `customer_ip_address ` to transactionItem model
- [ ] Add field `customerIpAddress` to transactionItem type
- [ ] Add field `customerIpAddress` to transactionInitialize mutation
- [ ] Add field `customerIpAddress` to transactionCreate & transactionUpdate
```

**Comment by mmiszy** [comment]
Is there an expected format for `customerIpAddress` or will anything work?

**Comment by korycins** [comment]
> Is there an expected format for `customerIpAddress` or will anything work?

Right, good question. We can validate if the provided format is  ipv4 or ipv6.

**Comment by NyanKiyoshi** [comment]
>  If `customerIPAddress` not provided Saleor will try to determine the customer's IP address on its own.

I would believe the app would be backend rather than a user-facing frontend. Thus if the app invokes the mutation (e.g. `transactionInitialize()`) without giving the IP address, Saleor would determine on its own the IP using the data it has at ends (HTTP headers, TCP packet). This seems like a potentially invalid flow as it would mean `customerIpAddress` would be the app's IP address (e.g. AWS, Vercel, etc.) rather than the user's actual IP address.

This would be misleading/improper as the staff user, and payment provider would expect a real user's IP address in this case.

I suggest if the IP address is not passed, then Saleor stores it as null value rather than trying to guess (a wrong value).

That's the flow I'm understanding would happen (interaction 3 and 5 are the problem): 

```mermaid
sequenceDiagram
    autonumber
    actor User
    participant Store as Storefront
    participant App as App Backend
    participant Core as Saleor Core
    participant DB as Database

    User->>Store: Starts a Checkout Session
    Store->>App: Starts Transaction
    Note over App,Core: Mutation requires HANDLE_PAYMENTS permission
    App->>Core: transactionInitialize() w/o IP
    alt IP address passed in input?
      Core->>Core: Uses IP Address from Input
    else
         Note over Core: IP address is the App's Backend IP
        Core->>Core: Determines IP Address from HTTP headers or TCP packet
    end
    Core->>DB: Stores IP Address
    Core-->>App: Returns Transaction
    App-->>Store: Returns a Response
    Store-->>User: [...]
```

**Comment by mmiszy** [comment]
@NyanKiyoshi When the user communicates with Saleor directly (like usual), the IP address should be determined by Saleor.

On the rare occasions when requests to Saleor are proxied through another backend, that backend will be responsible for determining the IP and sending it to Saleor in the `customerIpAddress` field.

**Comment by NyanKiyoshi** [comment]
> @NyanKiyoshi When the user communicates with Saleor directly (like usual), the IP address should be determined by Saleor.
> 
> On the rare occasions when requests to Saleor are proxied through another backend, that backend will be responsible for determining the IP and sending it to Saleor in the `customerIpAddress` field.

We are adding the new field to three mutations that require `HANDLE_PAYMENTS` permission: `TransactionCreate()`, `transactionInitialize()`, `TransactionUpdate()`.

This would mean that a storefront user is not supposed to get those mutations triggered directly from their machine, but instead through an app backend as it requires an app JWT token with proper permissions. If it wasn't the case (storefront directly calling the Core GraphQL backend) then the value could be forged.

My current understanding is that there should always be a middle-man for those mutations (if the app and storefront are following security best practices), and thus Saleor's guess would _always_ be wrong for `customerIpAddress` and thus not a reliable source for truth.

**Comment by mmiszy** [comment]
`transactionInitialize` is called by users directly, no permissions are required unless you want to override the `action`.

Wondering if we should also add `transactionProcess` to the list @korycins ? And do we need to add it to `transactionCreate` and `transactionUpdate`? I thought the IP is only needed _ad hoc_ by payment apps, it's not meant to be stored in Saleor?

**Comment by NyanKiyoshi** [comment]
> `transactionInitialize` is called by users directly, no permissions are required unless you want to override the `action`.

Answers my concern. I thought the mutation was only allowed to be invoked through apps 👍

**Comment by korycins** [comment]
Right. We don't need it for `transactionCreate` and `transactionUpdate`. Originally I was thinking about storing the customer IP address inside `TransactionItem` model. but it looks like we only want to pass it to the payment app. No need to save it. 
In that case, it has more sense to have a protected input field `customerIPAddress`  for `transactionInitalize` and `transactionProcess`. If not provided, Saleor will try to determine it. We will include it in the webhook payload but we will not store it. 
I will update the RFC. Thanks, guys for the review and your time.
