### ISSUE TITLE
Bug: Sales discounts applied multiple times

### ISSUE THREAD

**Issue by jakubkuc** [saleor/saleor#13661]
### What are you trying to achieve?

There's a specific case where using mutation `checkoutLinesAdd` for lines with product on sale will result in applying the discount two times. 
It happens only when in mutation query there is a resolver with dataloader that fetches `checokut_info` and  `discounts`, after that a `availablePaymentGateways` field is queried - which uses a root checkout object and fetches checkout_info instead of using dataloader.
This results in creating and attaching a discount object for checkout two times - once inside a resolver with dataloader and once in resolver for `availablePaymentGateways` - as its using`fetch_checkout_info` on `root` checkout object so in this scope it does not "see" discounts created in dataloader (it is not yet in the db). 

The approach to fix this issue will take 3 steps in separate PRs:

- [x] 1. Fix this specific case by changing `availablePaymentGateways` resolver to use checkout_info
- [ ] 2. Make sure that `fetch_checkout_info` is used only in mutations.  Resolvers and dataloaders should use `checkout_info` object loaded beforehand.
- [ ] 3. Implement `unique_together` to prevent a situation where the same discount is added two times into the same checkout line.

### Steps to reproduce the problem

1. Configure and activate Adyen plugin.
2. Create an empty checkout.
3. Add a line with variant that is on sale. Use mutation with specific fields queried like in example 
```
mutation addLineToNewCheckout($id: ID, $lines: [CheckoutLineInput!]!) {
  checkoutLinesAdd(id: $id, lines: $lines) {
    checkout {
      quantity
      availablePaymentGateways {
      name
      id
      }
      lines {
        id
        quantity
        unitPrice {
          gross {
            currency
            amount
          }
        }
      }
      subtotalPrice{ 
        gross{
          amount
        }
      }
      totalPrice {
        gross {
          currency
          amount
        }
      }
    }
  }
}
```
4. The bug is more visible when you use the same mutation two times (which should add another line with the same product variant).
### What did you expect to happen?

The prices are correctly calculated but in this case discount is added two times and the line `totalPrice` is incorrect

### Environment

Saleor version: 3.14

```[tasklist]
### Tasks
- [ ] https://github.com/saleor/saleor/issues/13662
- [ ] https://github.com/saleor/saleor/issues/13664
- [ ] https://github.com/saleor/saleor/issues/13665
```
