### ISSUE TITLE
[RFC] Allow taking draft orders into vouchers usage calculations

### ISSUE THREAD

**Issue by aniav** [saleor/saleor#13713]
## Problem

We aim to optionally calculate and validate vouchers within draft orders. While it's currently possible to add vouchers to these orders, they aren't computed as used.

---
## 1. General Assumptions

The proposed solution should build upon the current `VoucherCode` implementation. This strategy is chosen to avoid conflicts since the `VoucherCode` framework changes the manner we handle vouchers details.

### Acceptance Criteria

- Functional use case:
  - Error handling: Voucher related errors should be handled accordingly.
  - Other use-cases: Voucher codes can be used to identify voucher validity.
---

### Mutations
> Code Reference: `saleor/graphql/order/mutations/draft_order_create.py`
```python

class DraftOrderInput(BaseInputObjectType):
    # deprecate old voucher field 
    voucher = graphene.ID(
        description="ID of the voucher associated with the order.", name="voucher"
    )
    # new field
    voucher_code = graphene.String(description="Code to use the voucher.")
 
```
Extend validation in to return proper information about vouchers.
> Code Reference: `saleor/graphql/order/mutations/draft_order_complete.py`
```python
class DraftOrderComplete(BaseMutation):
    def perform_mutation(self):
        validate_draft_order(order, country, manager)
```

### Types
Extend `Channel.order_settings` with new `include_draft_order_in_voucher_usage` field

```python
class OrderSettings(ObjectType):
    include_draft_order_in_voucher_usage = graphene.Boolean(
        required=False,
        description=(
            "Turn this on to instantly apply vouchers to draft orders."
            "Please be careful, as this will reserve the voucher and might affect the time it takes for users to complete their transactions."
        ),
    ) 
```

> This will be added while using `npm run build-schema`
```graphql
type OrderSettings {
    includeDraftOrderInVoucherUsage: Boolean!
}
```

---

## 3. Database changes
Migration is needed to provide new field for our flag.
> Code Reference: `saleor/channel/models.py`
```python
class Channel(ModelWithMetadata):
    ...
    include_draft_order_in_voucher_usage = models.BooleanField(default=False)
```

This step also involves changes in `saleor/graphql/channel/mutations/utils.py` populating particular settings needs to be reflected in whole application.
Recently settings was changed from global to per Channel, this is the new approach in Saleor and should be reflected in that way.

---

## 4. Changes in the code
* `draftOrderCreate` and `draftOrderUpdate` mutation already enables voucher assignment. However, there's a need to enhance its functionality to ensure the voucher hasn't been previously utilized. This requires the following:
    * Augment the validation on the voucher field in `DraftOrderCreate/DraftOrderUpdate`. Utilize `clean_voucher()` to verify the voucher's status.
      ```python
      clean_voucher()
      ```
      
    * Update voucher usage statistics when it's integrated into a draft order. For the correct computation and application of discounts, adjust the `perform_mutation` function in the `DraftOrderComplete` mutation. This requires a function similar to `_process_voucher_data_for_order()`.
      > Code Reference: `saleor/checkout/complete_checkout.py`
      ```python
        def _process_voucher_data_for_order():
            if voucher.usage_limit:   
                ...
            if voucher.apply_once_per_customer: 
                ...
      ```
      and adjusting `validate_draft_order()` function to return proper validation errors.
  

* Adjustments are required to modify voucher usage metrics when a draft order is expunged. Specifically, the `DraftOrderDelete` mutation's `perform_mutation` function should be adapted to utilize our flag, determining voucher calculations. While `release_voucher_usage` was the initial function, in the current `VoucherCode` version, it's replaced by `release_voucher_code_usage`.
    > Code Reference: `saleor/discount/utils.py`
  ```python
  release_voucher_code_usage()
  ```

---

## 5. To Do list

```[tasklist]
### Tasks
- [ ] https://github.com/saleor/saleor/issues/14120
- [ ] https://github.com/saleor/saleor/issues/14178
- [ ] https://github.com/saleor/saleor/issues/14179
- [ ] https://github.com/saleor/saleor/issues/14180
- [ ] https://github.com/saleor/saleor/issues/14181
- [ ] https://github.com/saleor/saleor/issues/14287
- [ ] https://github.com/saleor/saleor/issues/14333
- [ ] https://github.com/saleor/saleor/issues/14439
```

---

## 6. To Test

- [ ] Verify the proper calculation of vouchers in draft orders.
- [ ] Validate the correct error handling for voucher-related issues.
- [ ] Ensure compatibility with existing voucher codes and systems.
- [ ] E2E validate one per customer functionality added by admin then check if user gets validation error that this voucher was already used.

## Other
* Checkout mutations that are involved with vouchers should recognize the new site settings. Given that draft orders don't currently contain a direct checkout, the `CheckoutCreateFromOrder` mutation can potentially instantiate a checkout from a draft order. It's pivotal to evaluate and discuss the appropriateness of this approach.

**Comment by aniav** [comment]
👍 from me

**Comment by fowczarek** [comment]
Ad. 3.
Should we use `OrderSettings` instead of `CheckoutSettings`? 
Should we store this field in `OrderSettings` instead of `Channel`?

**Comment by IKarbowiak** [comment]
@fowczarek changed. The setting will be added to `Channel.order_settings`

**Comment by IKarbowiak** [comment]
We should also consider what should happened when `include_draft_order_in_voucher_usage` is changing from `True` to `False`. IMO we should decrease voucher usage for all orders that are draft
