### ISSUE TITLE
Add authorization webhooks for order and checkout

### ISSUE THREAD

**Issue by korycins** [saleor/saleor#13804]
## Problem

We don't have async webhooks that could allow us to track the orders/checkouts that are (fully) authorized. We have such webhooks for (fully) paid order and fully paid checkout.

---

```[tasklist]
### To-do list 
- [ ] TBD
```

---

## 1. General Assumptions

We will add the missing webhooks:
`checkout-authorized` - some part of the checkout's total was authorized
`checkout-fully-authorized` - a full checkout's total amount was authorized
`order-authorized` - some part of the order's total was authorized
`order-fully-authorized` - a full order's total amount was authorized

Adding (skipping authorization, like auto-capture) charged funds to checkout/order will also trigger the authorize webhooks.  As to charge the funds, the funds need to be authorized first. These webhooks will work similarly to `checkout.authorizeStatus` and `order.authorizeStatus`.

> **Warning**
> The new webhooks will work only with TransactionAPI. The old PaymentAPI is not included in the scope.

### Acceptance Criteria

- [ ] New webhooks are available in graphql schema
- [ ] New webhooks have a webhook subscription definition
- [ ]  `checkout-authorized` webhook is called when checkout receives a new transaction that is authorized, charged, pending-authorized, pending-charged.  
- [ ] `checkout-fully-authorized` webhook is called when checkout's total <= sum(transactions: authorized, charged, pending-authorized, pending-charged).
- [ ] `order-authorized` webhook is called when an order receives a new transaction that is authorized or charged.
- [ ] `order-fully-authorized` webhook is called when an order's total <= sum(transaction: authorized, charged)
- [ ] new webhook events have a description when they are called
- [ ] The transactionInitialize, transactionProcess triggers new webhooks
- [ ] The `transactionCreate`, `transactionProcess` triggers new webhooks
- [ ] The `transactionEventReport` triggers new webhooks

#### Checkout-authorized
Requires: MANAGE_CHECHKOUTS
```graphql
"""
Event sent when checkout received a transaction with status: authorized, charged, authorize-pending, charge-pending
"""
type CheckoutAuthorized implements Event @doc(category: "Checkout") {
  """Time of the event."""
  issuedAt: DateTime

  """Saleor version that triggered the event."""
  version: String

  """The user or application that triggered the event."""
  issuingPrincipal: IssuingPrincipal

  """The application receiving the webhook."""
  recipient: App

  """The checkout the event relates to."""
  checkout: Checkout
}

```
#### Checkout-fully-authorized
Requires: MANAGE_CHECHKOUTS
```graphql
"""
Event sent when checkout's total is covered by transactions with statuses: authorized, charged, authorize-pending, charge-pending
"""
type CheckoutFullyAuthorized implements Event @doc(category: "Checkout") {
  """Time of the event."""
  issuedAt: DateTime

  """Saleor version that triggered the event."""
  version: String

  """The user or application that triggered the event."""
  issuingPrincipal: IssuingPrincipal

  """The application receiving the webhook."""
  recipient: App

  """The checkout the event relates to."""
  checkout: Checkout
}

```

#### Order-authorized
Requires: MANAGE_ORDERS
```graphql

"""
Event sent when order received transaction with status: authorized, charged
"""

type OrderAuthorized implements Event @doc(category: "Orders") {
  """Time of the event."""
  issuedAt: DateTime

  """Saleor version that triggered the event."""
  version: String

  """The user or application that triggered the event."""
  issuingPrincipal: IssuingPrincipal

  """The application receiving the webhook."""
  recipient: App

  """The order the event relates to."""
  order: Order
}

#### Order-fully-authorized
Requires: MANAGE_ORDERS

```graphql

"""
Event sent when order's total is covered by  transactions with statuses: authorized, charged
"""

type OrderFullyAuthorized implements Event @doc(category: "Orders") {
  """Time of the event."""
  issuedAt: DateTime

  """Saleor version that triggered the event."""
  version: String

  """The user or application that triggered the event."""
  issuingPrincipal: IssuingPrincipal

  """The application receiving the webhook."""
  recipient: App

  """The order the event relates to."""
  order: Order
}
```

**Comment by szczecha** [comment]
`The transactionCreate, transactionProcess triggers new webhooks` What about transactionUpdate?

**Comment by korycins** [comment]
Typo! Thanks @szczecha
