### ISSUE TITLE
Transactions - stable API

### ISSUE THREAD

**Issue by lkostrowski** [saleor/saleor#14186]
Issues to be completed to freeze transactions API and remove it from "preview" phase
```[tasklist]
### Tasks
- [ ] https://github.com/saleor/saleor/issues/14185
- [ ] https://github.com/saleor/app-marketplace-backend/issues/90
- [ ] https://github.com/saleor/saleor/issues/12491
- [ ] https://github.com/saleor/saleor/issues/12894
- [ ] https://github.com/saleor/saleor/issues/14149
- [ ] https://github.com/saleor/saleor/issues/14188
- [ ] https://github.com/saleor/saleor/issues/14196
- [ ] https://github.com/saleor/saleor/issues/14580
- [ ] https://github.com/saleor/saleor/issues/14770
```

**Comment by witoszekdev** [comment]
More issues: https://github.com/saleor/saleor/issues/14771
