### ISSUE TITLE
`orderConfirm` should capture TransactionItems that have action `CHARGE`

### ISSUE THREAD

**Issue by witoszekdev** [saleor/saleor#14346]
## Problem

`orderConfirm` mutation captures authorized Payments:
https://github.com/saleor/saleor/blob/ced055cebeb50871e5352da8285df11790c8ff72/saleor/graphql/order/mutations/order_confirm.py#L79C17-L79C17

We should add the same logic for TransactionItems that have action `CHARGE`

---

## 1. General Assumptions

Transactions that can be captured, are captured in `orderConfirm` mutation

### Acceptance Criteria

- [ ] When `orderConfirm` is run, we check for each existing transaction on the order
	- [ ] When `TransactionItem` has `action: ["CHARGE"]` we run the same logic as in `transactionRequestAction` mutation
- [ ] We should only charge the amount that's needed for the order's total
    - [ ] For example if our `order.total` is _100 USD_ and we have authorization for _110 USD_ we should only capture _100 USD_
- [ ] If the capture fails, we should also fail the `orderConfirm` mutation
    - [ ] If the transaction has [`authorizePendingAmount`](https://witoszek-dev.eu.saleor.cloud/graphql/#), but no [`authorizedAmount`](https://witoszek-dev.eu.saleor.cloud/graphql/#) then it means that the authorization is still pending and we cannot capture the Transaction

### Types

```graphql
enum OrderErrorCode {
	BILLING_ADDRESS_NOT_SET
	CANNOT_CANCEL_FULFILLMENT
	CANNOT_CANCEL_ORDER
	CANNOT_DELETE
	CANNOT_DISCOUNT
	CANNOT_REFUND
	CANNOT_FULFILL_UNPAID_ORDER
	CAPTURE_INACTIVE_PAYMENT
	GIFT_CARD_LINE
	NOT_EDITABLE
	FULFILL_ORDER_LINE
	GRAPHQL_ERROR
	INVALID
	PRODUCT_NOT_PUBLISHED
	PRODUCT_UNAVAILABLE_FOR_PURCHASE
	NOT_FOUND
	ORDER_NO_SHIPPING_ADDRESS
	PAYMENT_ERROR
	# PAYMENT_MISSING
	PAYMENT_OR_TRANSACTION_MISSING # name changed
	TRANSACTION_ERROR
	TRANSACTION_IS_PENDING # added
	REQUIRED
	SHIPPING_METHOD_NOT_APPLICABLE
	SHIPPING_METHOD_REQUIRED
	TAX_ERROR
	UNIQUE
	VOID_INACTIVE_PAYMENT
	ZERO_QUANTITY
	INVALID_QUANTITY
	INSUFFICIENT_STOCK
	DUPLICATED_INPUT_ITEM
	NOT_AVAILABLE_IN_CHANNEL
	CHANNEL_INACTIVE
}
```

## 5. To Do list

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

## 6. To Test

- [ ]
- [ ]

**Comment by witoszekdev** [comment]
Migrated: https://linear.app/saleor/issue/SHOPX-1753/mismatch-between-payments-vs-transaction-api-orderconfirm-doesnt
