### ISSUE TITLE
Bug: Unable to retry account confirmation after accountRegister 

### ISSUE THREAD

**Issue by kadewu** [saleor/saleor#14471]
## Problem

Users are not able to retry account confirmation for example when they lost confirmation link/token.
As for now, it's possible for user to retry confirmation when `Shop.allowLoginWithoutConfirmation`  is enabled with `sendConfirmationEmail` mutation, but it's not possible otherwise.
I would expect that `requestPasswordReset` will work for that case, but currently user will get error, that account is inactive which disable password reset.
Related issue: https://github.com/saleor/saleor/issues/5615

---

## 1. General Assumptions

1. User is able to retry account confirmation.
2. Retrying account confirmation will be possible with `requestPasswordReset`.

### Acceptance Criteria

- [] `requestPasswordReset` is able to confirm account (value of `Shop.allowLoginWithoutConfirmation` doesn't matter, this feature should work for both flows).
- [] Account that was disabled should not be able to reactivate account by doing `requestPasswordReset`.

## 2. To Do list

```[tasklist]
### Tasks
- [ ] Add docs for new feature and improve explanation around customer account creation in documentation as it seems confusing.
```
