### ISSUE TITLE
Take into account the allow_replica in WebhookPlugin

### ISSUE THREAD

**Issue by korycins** [saleor/saleor#14472]
## Problem
The main problem is described here: 
The linked issue set the allow_replica to always False. It means that we always use main DB to generate the payload. It was only a quick fix for previous Saleor's verions.

---

## 1. General Assumptions
- The WebhookPlugin should take into account the `allow_replica`, provided by PluginsManager.
- Each payload generated by WebhookPlugin should take into account `allow_replica` value. 
- The `allow_replica` input should be mandatory argument to all "trigger" methods/functions used in WebhookPlugin handlers.  Example:
```python
    def order_created(self, order: "Order", previous_value: Any) -> Any:
        if not self.active:
            return previous_value
        event_type = WebhookEventAsyncType.ORDER_CREATED
        if webhooks := get_webhooks_for_event(event_type):
            order_data_generator = partial(
                generate_order_payload, order, self.requestor
            )
            trigger_webhooks_async(
                None,
                event_type,
                webhooks,
                order,
                self.requestor,
                legacy_data_generator=order_data_generator,
                allow_replica=self.allow_replica # <---
            )
```
Probably we could introduce the wrapper on WebhookPlugin side that will set this value by default
- All get_plugins_manager calls (Explictly any methods/functions that creates the instance of PluginsManager) should explicitly pass the value `allow_replica`. (we should consider setting up this value as a mandatory - if we do, we should probably notify the cloud team. It sounds as the safest solution for future new webhook events).
- The calls of async webhook triggered by mutation should have set allow_replica to False
- The calls of sync webhook triggered by mutation should have set allow_replica to False
- The calls of sync webhook triggered by query should have set allow_replica to True ( keep in mind, that it is only for the query request, not the response of the mutation query)

### Acceptance Criteria

- [ ] The calls of async webhook triggered by mutation have set allow_replica to False
- [ ] The calls of sync webhook triggered by mutation have set allow_replica to False
- [ ] The calls of sync webhook triggered by query have set allow_replica to True 

### Mutations

No changes

### Types

No changes

## 3. Database changes

No changes

## 5. To Do list

```[tasklist]
### Tasks
```
