### ISSUE TITLE
Checkout / Order "problems" API

### ISSUE THREAD

**Issue by lkostrowski** [saleor/saleor#14580]
Epic gathering new "problems" API that will replace "errors" field in Order in the future and will stabilize user errors on checkout

```[tasklist]
### Tasks
- [ ] https://github.com/saleor/saleor/issues/12942
- [ ] Implement more "problems type" for checkout
- [ ] Implement "problems API" to the order object
- [ ] Implement "problems API" to shipping sync webhooks
- [ ] Introduce generic sync webhook response for error
- [ ] https://github.com/saleor/saleor/discussions/14584
- [ ] https://github.com/saleor/saleor/issues/12943
```

**Comment by lkostrowski** [comment]
Consider separate TaxAppProblem and FlatTaxesProblem for feature proofing

**Comment by lkostrowski** [comment]
Moved to internal Saleor backlog
