### ISSUE TITLE
Add the possibility to provide metadata in `transactionEventReport` mutation

### ISSUE THREAD

**Issue by witoszekdev** [saleor/saleor#14771]
## Problem

Payment apps cannot update `TransactionItem` metadata in `transactionEventReport` mutation. This causes the app to use separate `updateMetadata` mutation, which prolongs the execution time of sync webhook, which is limited to 20s.

Related: https://github.com/saleor/saleor/issues/14772

---

## 1. General Assumptions

Add `metadata` parameter to `transactionEventReport` which will update the metadata of Transaction the same way as, `updateMetadata` (i.e. it will merge existing metadata with new one, not replace everything).

### Acceptance Criteria

- [ ] `transactionEventReport` has `metadata` parameter
  - [ ] it merges existing metadata with new one

### Mutations

```graphql
  """
  Report the event for the transaction.

  Added in Saleor 3.13.

  Note: this API is currently in Feature Preview and can be subject to changes at later point.

  Requires the following permissions: OWNER and HANDLE_PAYMENTS for apps, HANDLE_PAYMENTS for staff users. Staff user cannot update a transaction that is owned by the app.
  """
  transactionEventReport(
    # ...
    
    """
    The ID of the transaction.
    """
    id: ID!

    # New:
    """
    Metadata to update on the `TransactionItem` object
    
    Added in Saleor 3.xx
    """
    metadata: [MetadataInput!]
  ): TransactionEventReport @doc(category: "Payments")
```

## 5. To Do list

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

## 6. To Test

- [ ]
- [ ]

**Comment by witoszekdev** [comment]
Released in [3.20.34](https://github.com/saleor/saleor/releases/tag/3.20.34)
