### ISSUE TITLE
Define gift reward for promotion rule

### ISSUE THREAD

**Issue by IKarbowiak** [saleor/saleor#15075]
## Problem

Allow providing the list of available gifts as a reward in the promotion rule.

Part of https://github.com/saleor/saleor/issues/12913

---

## 1. General Assumptions

- Allow a `gift` option as a reward in the promotion rule
- Allow providing the list of available variants that can be a gift
- Add a `gift` field to the promotion rule

### Calculation assumptions
- When `GIFT` reward type is chosen, the `gift` is required
- Update promotions calculations - chose best promotion rule that gives the best saving for user, include gift rules in the calculations
- For savings comparison choose the available variant from the promotion rule `gifts` list with the highest `discounted_price`
- Create an `OrderDiscount`/`CheckoutDiscount` object with the chosen promotion rule, If the gift rule has been chosen, create a corresponding `CheckoutLine`/`OrderLine` with `isGift` flag set to `True`
- The price for gift lines should be zero, and those lines shouldn't be sent to the tax plugins.

### Checkout/Order processing
- Update the checkout and order calculations, zero down the price of a gift item
- Handle case when the gift items are already in the cart - we should create a new line for the gift and mark it as a `gift`
- Do not allow to change the gift line quantity - the mutations for updating checkout and order line should be extended with proper validation
- Allow defining limit of gifts to choose in the API - always return 1 for now
- Do not allow removing gift line (otherwise the checkout will be calculated again and the gift will be assigned once again. We do not want to handle such case in MVP)
- Ensure that the checkout can be completed even if the gift line is out of stock. To make it as simple as possible, complete checkout anyway. The invalid gift should be handled by staff 

### Examples
- Buy 2 cups get a gift for free
> 💡 Gift defines a list of available gifts that the user can choose from. When the list has only one item it will be added automatically
```json
{
"promotionRule": {
"orderPredicate": {
 "AND": [
  {
   "discountedLineObjectPredicate": {
    "quantity": {
    	"range": {
    	  "gte": 2
    	}
    }
   }
  },
  {
   "discountedLineObjectPredicate": {
    "cataloguePredicate": {
    	"__typename": "ProductPredicate",
    	"name": {
    		"eq": "Cup"
    	}
    }
   }
  },
 ]
}
"rewardType": "GIFT",
"rewardValueType": null,
"rewardValue": 0,
"gifts": ["XYZ1", "XYZ2", "XYZ3"]
}
}
```

### Example flow
Staring conditions:
- first promotion rule is giving 10% discount on the whole order; applies on all products
- second promotion rule is a gift type rule and as a gift offer the gift that costs 10$; applies on all products
- third promotion rule is a gift type rule and as a gift offer the gift that costs 20$; applies on orders with total price above 100$

Case:
- user create a checkout for 50$
- only promotion rule 1 and 2 applies
- promotion rule 2 is giving more savings so it's applied
- the new gift line will be created; the price will be zero down
```json
{
  "checkout": {
    ...
    "lines": {
        "isGift": true,
        "quantity": 1,
        "unitPrice": {
            "gross": {
                "amount": 0
            }
        },
        "undiscountedUnitPrice" {
            "amount": 10 
        },
        "totalPrice" {
            "gross" {
                "amount": 0
            }
        },
        "undiscountedTotalPrice" {
            "amount": 10 
        }
    }
  }
}
```
- after checkout is completed, we will have the order line with an extra gift line
```json
{
  "order": {
    ...
    "lines": [{
        "isGift": true,
        "quantity": 1,
        "unitPrice": {
            "gross": {
                "amount": 0
            }
        },
        "undiscountedUnitPrice": {
            "amount": 10
        },
        "unitDiscount": {
              "amount": 10
        },
        "totalPrice": {
            "gross": {
                "amount": 0
            }
        },
        "undiscountedTotalPrice": {
            "amount": 10 
        }
       "unitDiscountType": "FIXED",  # ?
       "unitDiscountValue": 10,
       "unitDiscountReason": PromotionRuleId
    },
    ...
    ]
  }
}
```

### Acceptance Criteria

- [ ] When the gift rule is giving the 
- [ ] The price of chosen gifts are equal to 0
- [ ] The gift line cannot be removed
- [ ] The checkout could be completed with the gift line that is out of stock

### Docs
- [ ] Explain how the best discount is chosen, including gift case
- [ ] Add info that for now there is no option to change the assigned promotions
- [ ] Add info that the gift line cannot be removed for now
- [ ] Explain how the checkout complete process works in case out of stock gift assigned

### Mutations

- Update the promotion inputs with `giftIds` field
- Update the following mutations: `promotionCreate`, `PromotionRuleCreate`, `promotionRuleUpdate`:
  - Require the `giftIds` field when the `GIFT` reward type is chosen
  - `rewardValueType`, `rewardValue`, `rewardPredicate` should be empty - raise an `ValidationError` otherwise
  - Validate `giftIds` field - the provided IDs must be the `ProductVariant` IDs
- Update `CheckoutLinesUpdate` - don't allow to update quantity of lines marked as gift line
- Update `OrderLineUpdate` - don't allow to update quantity of lines marked as gift line
- Update `checkoutLineDelete` and `CheckoutLinesDelete` - do not allow deleting gift lines

```graphql
input PromotionRuleInput @doc(category: "Discounts") {
  ...
  giftIds: [ID!]
}

input PromotionRuleCreateInput @doc(category: "Discounts") {
  ...
  giftIds: [ID!]
}

input PromotionRuleUpdateInput @doc(category: "Discounts") {
  ...
   giftIds: [ID!]
}
```

### Types

- Extend `PromotionRule` with `giftIds`
- Extend `PromotionRule` with`giftsLimit` - will define the maximum number of gifts to choose from the gifts list. For now, we will always return 1, and it won't be configurable for now
- Extend `RewardTypeEnum` with GIFT 
- Extend `Checkout` with `availableDiscounts`
- Extend `Order` with `availableDiscounts`- the `availableDiscounts` should be returned only for draft orders
- Extend `OrderLine` and `CheckoutLine` with `is_gift` label
- Consider adding filter for getting lines that are `giftIds`

```graphql


type PromotionRule implements Node @doc(category: "Discounts"){
  ...
  giftIds: [ID!]
  giftsLimit: Int
}

enum RewardTypeEnum @doc(category: "Discounts") {
  ...
  GIFT
}

type OrderLine implements Node & ObjectWithMetadata @doc(category: "Orders") {
  ...
  isGift: Boolean!
}

type CheckoutLine implements Node & ObjectWithMetadata @doc(category: "Checkout") {
  ...
  isGift: Boolean!
}

```

## 3. Database changes

- Add a `gifts` field to `PromotionRule` model
- Add a `is_gift` to `CheckoutLine` model
- Add a `is_gift` to `OrderLine` model

```python
class PromotionRule:
    ...
    gifts: ManyToMany(ProductVariant)


class CheckoutLine:
    ...
    is_gift: BooleanField(default=False)

class OrderLine:
    ...
    is_gift: BooleanField(default-False)
```

## 4. To Do list

- [ ]  Extend the `rewardType` enum
- [ ]  Introduce the `gift` field
- [ ]  Update the mutations with proper validation
- [ ]  Update the order and checkout price recalculations
- [ ]  Ensure tax for flat rates and Avatax are properly calculated

## 5. Tasks
```[tasklist]
- [ ] https://github.com/saleor/saleor/issues/15223
- [ ] https://github.com/saleor/saleor/issues/15224
- [ ] https://github.com/saleor/saleor/issues/15225
```
