### ISSUE TITLE
Unify the timeouts for all webhooks

### ISSUE THREAD

**Issue by korycins** [saleor/saleor#15140]
## Problem
This is a continuation of the changes described [here](https://github.com/saleor/saleor/issues/13770) for all webhooks that we trigger. 
Some webhooks have different timeout than the default one. Like filter-shipping-methods .
We should unify the value for all webhooks that we have. The proposed value is (2, 18), where 2 seconds is for establishing the connection, and 18 for processing the received payload. 

---

### Acceptance Criteria

- [ ] All webhooks use the same timeout value
- [ ] Docs should include the timeout value that we set up in the core

### Tasks
- [ ] Unify the timeouts used for all webhooks (sync and async), and change them to (2, 18)
- [ ] Update docs to inform about the current timeout
- [ ] Remove the patch introduced in 3.14 for cloud (`extend-timeout-for-exclude-shipping-methods`) when releasing the changes.
