### ISSUE TITLE
Add flag to control the TTL of releasing funds for abandoned checkouts

### ISSUE THREAD

**Issue by korycins** [saleor/saleor#15238]
## Problem
In https://github.com/saleor/saleor/issues/14733 we introduced the logic for releasing the funds when checkout is abandoned. 
The logic operates there on hardcoded ttl - 6h. This is something that should be controlled by staff user. As the value could be different per store.
Docs about current flow: https://docs.saleor.io/docs/3.x/developer/checkout/overview#releasing-funds-for-abandoned-checkouts

---

## 1. General Assumptions
We will extend `channel.checkoutSettings`  to store TTL before releasing funds for abandoned checkouts. The implementation introduced in https://github.com/saleor/saleor/pull/14823 should operate on the value received from the staff. 

### Acceptance Criteria

- [ ] checkoutSettings has a new flag, which represents the TTL before releasing the funds on checkouts
- [ ] the release funds logic uses the value from the flag
- [ ] channel create & channel update mutation accept new input for new flag
- [ ] the migration is implemented as a zero downtime ( new field in channel. should have a default value on DB)

### Mutations

```graphql
input CheckoutSettingsInput @doc(category: "Checkout") {

  """
  Default 6 hours. The time in hours after any abandoned paid checkouts will be released.
  if 0 provided, the logic for releasing funds for checkouts will be disabled.
  """
  releaseFundsAfter: Hour
}
```

### Types

```graphql
"""The `Hour` scalar type represents number of hours by an integer value."""
scalar Hour
type CheckoutSettings {
  
  """
  Default 6 hours. The time in hours after any abandoned paid checkouts will be released."""
  releaseFundsAfter: Hour!
}
```

## 3. Database changes

Channel will receive a new field, which will store the TTL before releasing the funds.

## 4. To Do list

```[tasklist]
### Tasks
- [ ] Define if the TTL before releasing funds should be in minutes or hours. Probably in hours, but this is something that we should check before adding to the API
```

## 6. To Test

- [ ]
- [ ]
