### ISSUE TITLE
Channel flag to control charge action on order confirmation

### ISSUE THREAD

**Issue by korycins** [saleor/saleor#15242]
## Problem
With changes from https://github.com/saleor/saleor/issues/15239, https://github.com/saleor/saleor/issues/14347, https://github.com/saleor/saleor/issues/14346
We end up with the implementation when `auto-confirm`/`orderConfirm` always makes the charge-request, when the transaction is authorized. Some of the stores would not want to make a charge on order confirmation moment. For example, some stores make a charge when the package is ready to ship (but the order was confirmed earlier). 
We need to have the possibility to control the behavior of the charge action when order is confirmed. 

---

## 1. General Assumptions
We will add a flag to `Channel`: "automatically_charge_all_new_orders" (name is only proposition, can be changes if we will find the better one). The flag will be responsible for controlling the charge action behavior. This will allow to use "auto-confirm" flag with more flexibility. 
By adding the new flag we will have below cases:
- "auto-confirm": True "auto-charge": True - the payment should be charged immediately when we receive info about authorization. The order should be confirmed, when charged amount covers the order total.
- "auto-confirm" True, "auto-charge": False - we don't make a charge action on any authorized payments. The payment will be charged by an external system or by staff user. In that case, the order should be marked as confirmed when the charged amount covers the order.total
- "auto-confirm": False, "auto-charge": True: the payment should be charged immediately when we receive the info about authorization. The order will be confirmed manually by staff user.
- "auto-confirm": False, "auto-charge": False: we don't make a charge action on any authorized payments. Order needs to be marked as a confirmed manually.

The part related to "auto-confirm" should be already handled based on the  issue:  https://github.com/saleor/saleor/issues/15239

To keep zero-downtime compatibility, a new flag "auto-charge" should be set during the migration:
`if channel. automatically_confirm_all_new_orders is True -> automatically_charge_all_new_orders=True`
`if channel. automatically_confirm_all_new_orders is False -> automatically_charge_all_new_orders=False`
This will probably require a patch to the previous released version, as we need to be sure, that any channel creation/update will also update the new charge flag.

In case of multiple transactions assigned to order, the charge action should be called in order based on creation time. 
The amount from charge request should not exceed the order.total amount.

### Acceptance Criteria
- [ ] The new flag works as explained above
- [ ] Feature has zero-downtime migrations
- [ ] Docs contain the section that will explain all use cases
- [ ] Flag can be set from dashboard

### Mutations

```graphql
type OrderSettings {
    """ Determine if orders should be immediately charged when is authorized."""
  automaticallyChargeAllNewOrders: Boolean!
```

### Types

```graphql
input OrderSettingsInput @doc(category: "Orders") {
  """ Determine if orders should be immediately charged when is authorized."""
  automaticallyChargeAllNewOrders: Boolean
}
```

## 3. Database changes
Channel model should receive a new field for storing the flag that determines the auto charge action

## 4. UML diagrams

```mermaid

```

## 5. To Do list

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

## 6. To Test

- [ ]
- [ ]
