### ISSUE TITLE
Support Traceparent Header Propagation from Mutation Requests to Webhook Responses

### ISSUE THREAD

**Issue by Minister944** [saleor/saleor#16253]
## Problem

Currently, when Saleor sends a webhook, it includes a Traceparent header that it generates. However, there is no way to propagate a trace ID from the front end during a mutation, such as productUpdate, and receive the same trace ID in the webhook response.

## 1. General Assumptions
To improve the traceability and debugging process, we propose allowing clients to pass a Traceparent header during mutations. This header will then be included in the webhook responses, enabling consistent trace IDs across different parts of the system. This feature will help in linking front-end requests with back-end processes and webhook responses, providing a comprehensive view of the request flow and simplifying the debugging process.

### Acceptance Criteria
- [ ] The API should accept an optional Traceparent header in mutation requests.
- [ ] The same trace ID should be included in the webhook response if provided.

## 2. UML diagrams
Example:
```mermaid
sequenceDiagram
    participant Client
    participant SaleorAPI
    participant Webhook

    Client->>+SaleorAPI: productUpdate mutation with Traceparent header
    SaleorAPI->>+Webhook: Webhook event with the same Traceparent header
```

## 3. To Do list
```[tasklist]
### Tasks
- [ ] Implement logic to propagate the Traceparent header to webhook events.
- [ ] Update the documentation to include information about the new Traceparent header support.
- [ ] Add tests to ensure the Traceparent header is correctly passed through and included in webhooks.
```

## 4. To Test
- [ ] Validate that the documentation is updated and clear about the new functionality.
- [ ] Check that the system behaves as before if no Traceparent header is provided.
- [ ] Verify that if a Traceparent header is provided, it is included in the webhook response.
- [ ] Make sure mutations handle the incorrect format of the Traceparent header

CC @luqasz, @GrzegorzDerdak

**Comment by IKarbowiak** [comment]
@Minister944 thanks for the issue. We will discuss the idea internally and get back to you.

**Comment by maarcingebala** [comment]
FYI, we're working on a new telemetry implementation in Saleor Core that will rely entirely on OpenTelemetry. The new implementation will also support exchanging context between Saleor and other services according to the spec: https://www.w3.org/TR/trace-context/. Check out the `otel` branch for more details; however, at this point, it contains only basic telemetry, while context propagation will be added in the following weeks.
