### ISSUE TITLE
Enhance product metadata filtering to support multiple values per key

### ISSUE THREAD

**Issue by SJCaldwell** [saleor/saleor#16464]
## Problem
I have products that all share the same keys in their metadata but with different values.
What I would like to do is to be able to do a where clause where a single key could be multiple values, similarly
to the `products` query `where` clause allowing a list of ids and saleor returning all the products
that have the matching value in the key.

Currently I can search products by metadata key val which returns all products with the same key and value pair. This; however,
doesn't quite cover my use case and I'm wondering how hard it would be to extend the metadata filtering ability to allow something like:

```graphql
products(
    first: 10
    channel: "default-channel"
    after: ""
    where: {metadata: {key: "my_key", values: ["1","2","3","4"]}}
) {...}
```

This would be a lot more ergonomic than chaining multiple and/or statements after another to achieve similar results.

---

## 1. General Assumptions
Currently doing something like:
```sql
select 
	...
from product_product
where 
metadata @> '{"field": "val"}' or
metadata @> '{"field": "val2"}' or
metadata @> '{"field": "val3"}' 
```
Takes quite a bit of time to get many products with same key but different key values.
Did see that postgres allows quite specific indexing on metadata so something like this could help 
to increate the query perf I'd imagine. https://www.postgresql.org/docs/current/datatype-json.html#JSON-INDEXING

### Acceptance Criteria

- [ ] As user of the API I should be able to query products where product metadata key is some value in a list of values

### Mutations
Extend existing `products` query parameters

```graphql
products(
    first: 10
    channel: "default-channel"
    after: ""
    where: {metadata: {key: "my_key", values: ["1","2","3","4"]}}
) {...}

```

### Types

```graphql
type MetadataKeyValues {
	key: String!
	values: [String!]!
}

```

## 3. Database changes
As discussed in the above, either recommendations to index specific keys on postgres or
having better pre-determined indexes on product metadata like GIN

## 4. UML diagrams

```mermaid

```

## 5. To Do list

```[tasklist]
### Tasks
- [ ] Index on product_product metadata to allow multiple value search
- [ ] `products` query where argument for metadata key values
```

## 6. To Test

- [ ]
- [ ]

**Comment by aniav** [comment]
Hey @SJCaldwell thank you for your report, this sounds as a reasonable thing to add. Feel free to make a contribution with the changes 🙌
