### ISSUE TITLE
Upgrade urllib3 from 1.x to 2.x

### ISSUE THREAD

**Issue by NyanKiyoshi** [saleor/saleor#17130]
## Problem

We currently still depend on an old version of urllib3 (v1.26.x), we should upgrade to the latest version (v2.2.x). `requests` supports urllib3 2.x since `requests==2.30.0`[^1]

Issues:
1. It's currently unclear for how long the v1.x major version will remain supported for.
2. `types-requests` only supports `urllib3>=2.0`[^2] which causes us to have outdated typing
3. Semgrep cannot be updated past `v1.52.0`

## Steps

```[tasklist]
### Tasks
- [ ] Check migration guide: https://urllib3.readthedocs.io/en/stable/v2-migration-guide.html
- [ ] Make required changes and upgrade urllib3 to latest v2.x
- [ ] Upgrade `types-requests` to the same version as `requests`
```

[^1]: https://github.com/psf/requests/issues/6432#issuecomment-1676067621
[^2]: https://github.com/python/typeshed/blob/c606b4f8ad36d363a7ec5193f5f8f88d7491bdbc/stubs/requests/METADATA.toml#L4
